// Scenario Launch

function execDialog()

{

	try {

		var scn = System.inputString("Load Scenario", "Enter the scenario file to execute",

									 Storages.extractStorageName(kag.currentStorage));

		if (scn != "") {

			kag.setConductorToMain(); // If extraconductor is in use, return to main

			kag.conductor.clear();

			kag.process(scn, "");

			return true;

		}

	} catch(e) {

		Debug.notice("Could not execute scenario : " + e.message);

	}

}