//;# MessageLayer.tjs - Message Layer

//;# Copyright (C)2001-2008, W.Dee and contributors  Modification and distribution are free.

//;<<'END_OF_TJS_SCRIPT';



// This script is also a valid perl5 script, and

// it uses perl to update the list of variables actually copied in assign/store/restore.

// Perform update with:

// perl MessageLayer.tjs

// ( The content of the process could be written sufficiently in TJS2, but unfortunately

//   an execution environment like perl does not exist or has not been made for TJS2 )



class LinkButtonLayer extends ButtonLayer

{

	// Layer for operating as a graphical button

	var linkNum; // Link number

	var onenter; // To be executed when the mouse enters

	var onleave; // To be executed when the mouse leaves



    var _eventTransparent;

    var _focusable;

	var _enabled;

    

	function LinkButtonLayer(win, par)

	{

		// Constructor

        super.ButtonLayer(...);

		focusable = false; // Does not receive focus

		enabled  = true;

        eventTransparent = false;

        hint = "";

	}



	function finalize()

	{

		super.finalize(...);

	}



	function onClick()

	{

        super.onClick(...);

	}



	function onExecute(x, y, button, shift)

	{

        if(enabled && button == mbLeft && !parent.selProcessLock) parent.onButtonClick(linkNum);

        if(this isvalid) super.onExecute(...);

	}



    function onMouseDown(x, y, button)

	{

		super.onMouseDown(...);

        if (button == mbRight) {

			releaseCapture();

            window.onPrimaryRightClick();

        }

	}

    

	function onMouseEnter()

	{

		parent.keyLink = linkNum;

		if (window.focusedLayer === null) with (parent) {

			// Temporarily lock parent and focus

			var lock = .selProcessLock;

			.selProcessLock = true;

			.focus();

			.selProcessLock = lock;

		}

		if(!parent.selProcessLock && onenter !== void) Scripts.eval(onenter);

		super.onMouseEnter(...);

	}



	function onMouseLeave()

	{

		parent.keyLink = -1 if (parent.keyLink == linkNum);

		if(!parent.selProcessLock && onleave !== void) Scripts.eval(onleave);

		super.onMouseLeave(...);

	}



	function assign(src)

	{

		super.assign(src);

        name = src.name;

        linkNum = src.linkNum;

		onenter = src.onenter;

		onleave = src.onleave;

		hint = src.hint;

		_enabled          = src._enabled;

		_focusable        = src._focusable;

		_eventTransparent = src._eventTransparent;

		internalUpdateProperty();

	}



	function internalUpdateProperty() {

		var en = super.enabled = getEnabled();

		if (en) {

			hitType = _eventTransparent ? htProvince : htMask; 

			// Since button images do not have area images,

			// setting hitType to htProvince will always

			// cause mouse events to pass through.

			super.focusable = _focusable;

		} else {

			hitType = htProvince;

			super.focusable = false;

		}

	}



    property enabled {

        // Whether it's enabled

        // If disabled, let events pass through

        setter(x) {

			_enabled = x;

			internalUpdateProperty();

        }

        getter() {

            return _enabled;

        }

    }

    

	property eventTransparent

	{

		// Whether to pass through events

		setter(x)

		{

			if(_eventTransparent != x)

			{

				_eventTransparent = x;

				internalUpdateProperty();

			}

		}

		getter()

		{

			return _eventTransparent;

		}

	}



	property focusable

	{

		// Whether to receive focus

		setter(x)

		{

			_focusable = x;

			internalUpdateProperty();

        }

        getter()

		{

            return _focusable;

		}

	}



    property toggle {

        getter() {

            return super.toggle;

        }

        setter(v) {

            super.toggle = v;

			if (radio) {

				parent.updateRadio(this) if (v);

				enabled   = _enabled;

				focusable = _focusable;

            }

        }

    }

	property radio { getter { return groupName != ""; } }

	function getEnabled(en = _enabled) { return en && !(radio && toggle); }

	function canExecute() { return getEnabled() && (hitType == htMask && hitThreshold < 256); }



}



class LinkCheckBoxLayer extends CheckBoxLayer

{

	// Checkbox to be managed as a "link" in the message layer

	var linkNum; // Link number

	var exp; // Expression

    var changefuncdata;

    var changefunc; // Change function

    var change; // Change expression

    var changese; // SE on change

    var vertical; // Vertical writing mode



	function LinkCheckBoxLayer(win, par)

	{

		// Constructor

		super.CheckBoxLayer(...);

		joinFocusChain = false; // Do not participate in focus chain

		hint = "";

	}



	function finalize()

	{

		super.finalize(...);

	}



	function assign(src)

	{

		super.assign(src);

        name = src.name;

		linkNum = src.linkNum;

		vertical = src.vertical;

		hint = src.hint;

		exp = src.exp;

        changefuncdata = src.changefuncdata;

        changefunc = src.changefunc;

        change = src.change;

        changese = src.changese;

	}



	function onKeyDown(key, shift, process)

	{

		// Swap right and left when in vertical writing mode

		if(vertical)

		{

			if(key == VK_LEFT) key = VK_RIGHT;

			else if(key == VK_RIGHT) key = VK_LEFT;

		}

		super.onKeyDown(key, shift, process);

	}



	function onSearchPrevFocusable(layer)

	{

		super.onSearchPrevFocusable(parent.findPrevFocusable(this, layer));

	}



	function onSearchNextFocusable(layer)

	{

		super.onSearchNextFocusable(parent.findNextFocusable(this, layer));

	}



	function onFocus(prevfocused, direction)

	{

		parent.keyLink = linkNum;

		super.onFocus(...);

	}



	function commit()

	{

		if (exp == "") return;

		kag.inputTemp = checked;

		try { Scripts.eval(("(" + exp + ") = kag.inputTemp")); } catch {}

	}



    function onChange(checked)

    {

        if (changefunc !== void) {

            Scripts.eval(changefunc)(checked, changefuncdata);

        } else if (change !== void) {

            kag.inputTemp = checked;

            Scripts.eval(("(" + change + ") = kag.inputTemp"));

            if (changese !== void) {

                Scripts.eval(changese);

            }

        }

    }



	function onMouseDown(x, y, button)

	{

		super.onMouseDown(...);

        if(button == mbRight) {

			releaseCapture();

            window.onPrimaryRightClick();

        }

	}

}





class LinkEditLayer extends EditLayer

{

	// Single-line edit layer to be managed as a "link" in the message layer

	var linkNum; // Link number

	var exp; // Expression



	function LinkEditLayer(win, par)

	{

		// Constructor

		super.EditLayer(...);

		joinFocusChain = false; // Do not participate in focus chain

		hint = "";

	}



	function finalize()

	{

		super.finalize(...);

	}



	function assign(src)

	{

		super.assign(src);

        name = src.name;

		linkNum = src.linkNum;

		exp = src.exp;

	}



	function onKeyDown(key, shift, process)

	{

		// Swap right and left when in vertical writing mode

		if(Edit_vertical)

		{

			if(key == VK_LEFT) key = VK_RIGHT;

			else if(key == VK_RIGHT) key = VK_LEFT;

		}

		// Correct keyLink when moving

		switch (key) {

		case VK_LEFT: case VK_RIGHT: case VK_UP: case VK_DOWN: case VK_RETURN: case VK_TAB:

			parent.keyLink = linkNum;

			break;

		}

		super.onKeyDown(key, shift, process);

	}



	function onSearchPrevFocusable(layer)

	{

		super.onSearchPrevFocusable(parent.findPrevFocusable(this, layer));

	}



	function onSearchNextFocusable(layer)

	{

		super.onSearchNextFocusable(parent.findNextFocusable(this, layer));

	}



	function onFocus(prevfocused, direction)

	{

		parent.keyLink = linkNum;

        super.onFocus(...);

	}



	function commit()

	{

		if (exp == "") return;

		kag.inputTemp = text;

		try { Scripts.eval(("(" + exp + ") = kag.inputTemp")); } catch {}

	}



	function onMouseDown(x, y, button)

	{

		super.onMouseDown(...);

        if(button == mbRight) {

			releaseCapture();

            window.onPrimaryRightClick();

        }

	}

}



class LinkSliderLayer extends SliderLayer

{

    // Slider to be managed as a "slider" in the message layer

	var linkNum; // Link number

	var onclick; // Executed when dragging stops

	var onenter; // Executed when mouse enters

	var onleave; // Executed when mouse leaves



    var exp; // Expression

    var changefuncdata;

    var changefunc; // Change function

    var change; // Change expression

    var changese; // SE on change



    function LinkSliderLayer(win, par)

    {

        // Constructor

        super.SliderLayer(...);

        joinFocusChain = false;

        hint = "";

    }

    

	function finalize()

	{

		super.finalize(...);

	}



	function assign(src)

	{

		super.assign(src);

        name = src.name;

		linkNum = src.linkNum;

		onclick = src.onclick;

		onenter = src.onenter;

		onleave = src.onleave;

		exp = src.exp;

        changefuncdata = src.changefuncdata;

        changefunc = src.changefunc;

        change = src.change;

        changese = src.changese;

	}



	function onSearchPrevFocusable(layer)

	{

		super.onSearchPrevFocusable(parent.findPrevFocusable(this, layer));

	}



	function onSearchNextFocusable(layer)

	{

		super.onSearchNextFocusable(parent.findNextFocusable(this, layer));

	}



	function onFocus(prevfocused, direction)

    {

        parent.keyLink = linkNum;

        super.onFocus(...);

	}



	function commit()

	{

		if (exp == "") return;

		kag.inputTemp = position;

		try { Scripts.eval(("(" + exp + ") = kag.inputTemp")); } catch {}

	}



    function onChange(position, dragging)

    {

        if (changefunc !== void) {

            Scripts.eval(changefunc)(position, dragging, changefuncdata);

        } else if (change !== void) {

            kag.inputTemp = position;

            Scripts.eval(("(" + change + ") = kag.inputTemp"));

            if (changese !== void && !dragging) {

                Scripts.eval(changese);

            }

        }

    }



	function onMouseEnter()

	{

        parent.keyLink = linkNum;

        if(!parent.selProcessLock && onenter !== void) Scripts.eval(onenter);

        super.onMouseEnter(...);

	}



	function onMouseLeave()

	{

		if(!parent.selProcessLock && onleave !== void) Scripts.eval(onleave);

		super.onMouseLeave(...);

	}



	function execClick() {

		if (onclick!== void && enabled && !parent.selProcessLock) Scripts.eval(onclick);

	}

	function  toLeft()  {

		super.toLeft(...);

		execClick();

	}

	function  toRight() {

		super.toRight(...);

		execClick();

	}

	function toPosition(x, y, drag = false) {

		super.toPosition(...);

		execClick() if (!drag || !Slider_dragging);

	}



	function onMouseDown(x, y, button)

	{

		super.onMouseDown(...);

        if(button == mbRight) {

			releaseCapture();

            window.onPrimaryRightClick();

        }

	}



	function onKeyDown(key, shift)

	{

		// Key pressed

		if(window.preProcessKeys(key, shift)) return;

		return super.onKeyDown(...);

	}



}



/**

 * System Button Extension

 * Extension of KAG sample plugin

 */

class SystemButtonLayer extends ButtonLayer

{

    var noStable; // Enabled even when not in Stable state

    var onclick; // Executed on click

    var onenter; // Executed when mouse enters

    var onleave; // Executed when mouse leaves



    /**

     * Constructor

     * @param window Window

     * @param parent Message Layer

     * @param init Generation info (held for recovery)

     */

    

	function SystemButtonLayer(window, parent)

	{

		super.ButtonLayer(window, parent);

		focusable = false;

		visible = true;

        onenter = void;

        onleave = void;

        onclick = void;

        noStable = void;

		hint = "";

    }



	function finalize()

	{

		super.finalize(...);

	}



	function onMouseEnter()

	{

        if(onenter !== void) Scripts.eval(onenter);

		super.onMouseEnter(...);

	}



	function onMouseLeave()

	{

        if(onleave !== void) Scripts.eval(onleave);

        super.onMouseLeave(...);

	}

    

	function onExecute(x, y, button, shift)

	{

        if (enabled && button == mbLeft && onclick !== void && (noStable || window.inStable)) {

            Scripts.eval(onclick);

        }

        if (isvalid this) {

            super.onExecute(...);

        }

    }



	function onMouseDown(x, y, button)

	{

		super.onMouseDown(...);

        if(button == mbRight) {

			releaseCapture();

            window.onPrimaryRightClick();

        }

	}

    

    function assign(src) {

        super.assign(src);

        name = src.name;

        onclick = src.onclick;

        onenter = src.onenter;

        onleave = src.onleave;

        noStable = src.noStable;

        enabled = src.enabled;

		hint = src.hint;

		hitType  = src.hitType;

		absolute = src.absolute if (src.absoluteOrderMode);

    }

}



/**

 * Layer that synchronizes relatively with another layer regarding display state and level

 */

class RelativeLayer extends AnimKAGLayer

{

	function finalize() {

		super.finalize(...);

	}

	var owner;



	var _visible;

	property visible {

		getter()  { return _visible; }

		setter(v) {

			_visible = v;

			v = v && owner.visible if (!_noRelative);

			super.visible = v;

		}

	}



	var _absolute;

	property absolute {

		getter()  { return _absolute; }

		setter(v) {

			_absolute = v;

			v += owner.absolute if (!_noRelative);

			super.absolute = v;

		}

	}



	var _noRelative;

	property noRelative {

		getter()  { return _noRelative; }

		setter(v) {

			_noRelative = v;

			rerelative();

			repos();

		}

	}



    // Origin correction processing

	var _originMode = 0;

	property originMode {

		getter()  { return _originMode; }

		setter(v) {

			_originMode = v;

			repos();

		}

	}



	property baseLeft { getter { return _noRelative ? 0 : owner.left + owner.diffx; } }

	property baseTop  { getter { return _noRelative ? 0 : owner.top  + owner.diffy; } }



	var _left;

	property left {

		setter(v) {

			var x = baseLeft + (_left = +v);

			switch (_originMode) {

			case 0: case 7: case 6:                 break;

			case 1: case 8: case 5: x -= width / 2; break;

			case 2: case 3: case 4: x -= width;     break;

			}

			super.left = x;

		}

		getter() {

			return _left;

		}

	}



	var _top;

	property top {

		setter(v) {

			var y = baseTop + (_top = +v);

			switch (_originMode) {

			case 0: case 1: case 2:                  break;

			case 7: case 8: case 3: y -= height / 2; break;

			case 6: case 5: case 4: y -= height;     break;

			}

			super.top = y;

		}

		getter() {

			return _top;

		}

	}



	function setPos(l, t, w=void, h=void) {

		super.width  = (int)w if w !== void;

		super.height = (int)h if h !== void;

		left = (int)l;

		top  = (int)t;

	}

	function setSize() {

		super.setSize(...);

		repos();

	}

	function setSizeToImageSize() {

		super.setSizeToImageSize(...);

		repos();

	}

	property width  { getter { return super.width;  } setter(v) { super.width  = v; repos(); } }

	property height { getter { return super.height; } setter(v) { super.height = v; repos(); } }



	function assignImages(src, copyvisiblestate = false)

	{

        super.assignImages(src);

        if (copyvisiblestate) {

            var su = super;

            visible  = src.visible;

            opacity  = src.opacity;

            absolute = src.absolute if !src.isPrimary && src.parent.absoluteOrderMode;

            _originMode = src._originMode;

			if (_noRelative != src._noRelative) {

				_noRelative  = src._noRelative;

				rerelative();

			}

            su.type = src.type;

            setPos(src.left, src.top, src.width, src.height);

            su.setImagePos(src.imageLeft, src.imageTop);

        }

    }



	function loadImages(storage, key)

	{

		var ret = super.loadImages(...);

		repos();

		return ret;

	}

	function repos() {

		top  = _top;

		left = _left;

	}

	function rerelative() {

		parent   = _noRelative ? owner : owner.parent;

		absolute = absolute;

	}



	function store() {

		var dic = super.store();

		dic.originMode = originMode;

		dic.noRelative = noRelative;

		return dic;

	}



	function restore(dic) {

		super.restore(dic);

		_originMode = dic.originMode if dic.originMode !== void;

		_noRelative = dic.noRelative if dic.noRelative !== void;

		rerelative();

		repos();

	}



	function RelativeLayer(owner) {

		this.owner = owner;

		super.AnimKAGLayer(owner.window, owner.parent);

		_noRelative = false;

		setPos(0,0,8,8);

		absolute = 1;

		visible = false;

	}



	/**

	 * Change to specified size considering the origin

	 */

	function syncSizeTo(w, h) {

		if (width != w || height != h || imageWidth != w || imageHeight != h) {

			var lay = window.temporaryLayer;

			with (lay) {

				.setSize(w,h);

				.fillRect(0,0,.width,.height,.neutralColor);

				switch (_originMode) {

				case 0: .copyRect(0,0,this,0,0,width,height); break;

				case 1: .copyRect((w-width)/2,0,this,0,0,width,height);break;

				case 2: .copyRect((w-width),0,this,0,0,width,height);break;

				case 3: .copyRect((w-width),(h-height)/2,this,0,0,width,height);break;

				case 4: .copyRect((w-width),(h-height),this,0,0,width,height);break;

				case 5: .copyRect((w-width)/2,(h-height),this,0,0,width,height);break;

				case 6: .copyRect(0,(h-height),this,0,0,width,height);break;

				case 7: .copyRect(0,(h-height)/2,this,0,0,width,height);break;

				case 8: .copyRect((w-width)/2,(h-height)/2,this,0,0,width,height);break;

				}

			}

			super.setSize(w,h);

			super.setImagePos(0,0);

			super.setImageSize(w,h);

			copyRect(0,0,lay,0,0,width,height);

			repos();

		}

	}



	/**

	 * Match size to target

	 */

	function syncSize(target) {

		if (target instanceof "RelativeLayer") {

			var w = Math.max(target.width, width);

			var h = Math.max(target.height, height);

			syncSizeTo(w, h);

			target.syncSizeTo(w, h);

		}

	}

}



class NameLayer extends RelativeLayer

{

	function finalize() {

		super.finalize(...);

	}

	function NameLayer(owner) {

		super.RelativeLayer(...);

	}



    /**

     * Text drawing

     * @param x X-coordinate

     * @param y Y-coordinate

     * @param text Display text

     */

    function draw(x, y, text) {

		with (owner) .drawTextToLayer(this, x, y, text, .chColor);

    }



	// Horizontal text alignment (-1: left, 0: center, 1: right)

	var align = -1;

	// Vertical text alignment

	var valign = -1;



	/**

	 * Name processing

	 */

	function processName() {

		if (owner.nameImageMap !== void) processNameImage(...);

		else                             processNameText( ...);

	}



	/**

	 * Name processing (Text version)

	 */

	function processNameText(text) {

		if (text != "") {

			fillRect(0, 0, width, height, 0);

			var x = 0, y = 0;

			if (align >= 0) {

				var w = font.getTextWidth(text);

				x = width - w;

				x \= 2 if (align == 0);

			}

			if (valign >= 0) {

				var h = font.getTextHeight(text);

				y = height - h;

				y \= 2 if (valign == 0);

			}

			draw(x, y, text);

			visible = true;

		} else {

			visible = false;

		}

	}



	/**

	 * Name processing (Image version)

	 */

	function processNameImage(text) {

		if (text != "") {

			var image = owner.nameImageMap[text];

			// If not found, use default

			if (image == "") image = owner.defaultNameImage;

			// If still no image, use text

			if (image == "") return processNameText(...);

			loadImages(image);

			visible = true;

		} else {

			visible = false;

		}

	}

	function store() {

		var dic = super.store();

		dic.align  = align;

		dic.valign = valign;

		return dic;

	}

	function restore(dic) {

		align  = dic.align  if (dic.align  !== void);

		valign = dic.valign if (dic.valign !== void);

		return super.restore(dic);

	}

}



class FaceLayer extends RelativeLayer

{

	function finalize() {

		super.finalize(...);

	}

	function FaceLayer(owner) {

		super.RelativeLayer(...);

	}



	function onTransitionCompleted(dest, src)

	{

		super.onTransitionCompleted(...);

		owner.swapFaceLayer();

	}

}

class MessageLineLayer extends KAGLayer      { function finalize { super.finalize(...); } function MessageLineLayer { super.KAGLayer     (...); } }

class MessageTextLayer extends RelativeLayer { function finalize { super.finalize(...); } function MessageTextLayer { super.RelativeLayer(...); } }



class AnimKAGLayerTransMove extends AnimKAGLayer, KAGTransMove {



	function AnimKAGLayerTransMove() {

		global.AnimKAGLayer.AnimKAGLayer(...);

		global.KAGTransMove.KAGTransMove();

	}



	function finalize() {

		global.KAGTransMove.finalize();

		global.AnimKAGLayer.finalize();

	}

}



class MessageLayer extends AnimKAGLayerTransMove

{

    var myleft;

    var mytop;

    var diffx  = 0;

    var diffy  = 0;



    function setDiff(diffx, diffy) {

        this.diffx = (int)diffx;

        this.diffy = (int)diffy;

        super.left = myleft + this.diffx;

        super.top  = mytop  + this.diffy;

		subLayersRePosition();

    }



    property left {

        setter(v) {

            myleft = (int)v;

            super.left = myleft + diffx;

			subLayersRePosition();

        }

        getter() {

            return myleft;

        }

    }



    property top {

        setter(v) {

            mytop = (int)v;

            super.top = mytop + diffy;

			subLayersRePosition();

        }

        getter() {

            return mytop;

        }

    }



    function setPos(l, t, w=void, h=void) {

        left = (int)l;

        top  = (int)t;

        width  = (int)w if w !== void;

        height = (int)h if h !== void;

    }

	function subLayersRePosition() {

		faceLayer.stopTransition() if faceLayer !== void;

		doSubLayers(function { repos(); });

	}

	function subLayersReAbsolute() {

		faceLayer.stopTransition() if faceLayer !== void;

		doSubLayers(function { rerelative(); });

	}

	function subLayersReVisible() {

		faceLayer.stopTransition() if faceLayer !== void;

		doSubLayers(function { visible = visible; });

	}

	function subLayersReOpacity(v) {

		faceLayer.stopTransition() if faceLayer !== void;

		doSubLayers(function(v) { opacity = v; }, v);

	}

	var subLayers;

	function doSubLayers(callback, *) {

		(callback incontextof faceLayer)(*) if faceLayer !== void;

		(callback incontextof nameLayer)(*) if nameLayer !== void;

		(callback incontextof textLayer)(*) if hasTextLayer;

		if (subLayers !== void)

			for (var i = subLayers.count-1; i >= 0; i--)

				(callback incontextof subLayers[i])(*);

	}



    /**

     * Inner opacity change processing

     * Control associated layers as well

     */

    function setInnerOpacity(v) {

        if (v !== void) {

            //dm("Internal opacity specified:" + v);

            super.opacity = v;

			subLayersReOpacity(v);

        }

    }



    /**

     * Inner visibility change processing

     * Control associated layers as well

     */

    function setInnerVisible(v) {

        if (v !== void) {

            //dm("Internal visibility specified:" + v);

            super.visible     = v;

			_visible <-> v;

			subLayersReVisible();

			_visible <-> v;

        }

    }



    /**

     * Return to the originally specified final display state/opacity

     * and cancel any ongoing fade.

     */

    function fadeDone() {

        //dm("Window display process finished");

        setInnerOpacity(_opacity);

        setInnerVisible(_visible);

        _fadeTimer.enabled = false;

        if (window.isMain && window.conductor !== void) {

            window.trigger("msgvisible");

        }

    }

    

    // Opacity

    var _opacity;

    property opacity {

        setter(v) {

            _opacity = v;

            fadeDone();

        }

        getter() {

            return _opacity;

        }

    }



    // Visibility state

    var _visible;

    property visible {

        setter(v) {

            _visible = v;

            fadeDone();

			storeRedrawTextState("setVisibleTime", v, 0);

        }

        getter() {

            return _visible;

        }

    }



    var _fadeTimer;

    var _fadeStartTime;

    var _fadeTime;

    var _startOpacity;

    var _toOpacity;

    

    function fadeHandler() {

        var now = System.getTickCount() - _fadeStartTime;

        if (now >= _fadeTime) {

            fadeDone();

        } else {

            setInnerOpacity(_startOpacity + (_toOpacity - _startOpacity) * now / _fadeTime);

        }

    }



    /**

     * Automatically adjust fade depending on visibility

     */

    function setVisibleTime(v, time) {

        if (v != visible) {

            //dm("Window fade display process:" + v);

            _visible = v;

            if (time > 0) {

                _fadeStartTime = System.getTickCount();

                _fadeTime      = time;

                _startOpacity = v ? 0 : _opacity;

                _toOpacity    = v ? _opacity : 0;

                setInnerOpacity(_startOpacity);

                setInnerVisible(true);

                _fadeTimer.enabled = true;

            } else {

                fadeDone();

            }

        } 

		storeRedrawTextState("setVisibleTime", v, 0);

    }



    // Display position

    property absolute {

        setter(v) {

            super.absolute = v;

			subLayersReAbsolute();

        }

        getter() {

            return super.absolute;

        }

    }

    

    var wwFollowing = "%),:;]}｡｣ﾞﾟ。，、．：；゛゜ヽヾゝ"

                "ゞ々’”）〕］｝〉》」』】°′″℃¢％‰　"; // Line-start prohibition characters

	var wwFollowingWeak="!.?､･ｧｨｩｪｫｬｭｮｯｰ・？！ーぁぃぅぇぉっゃゅょゎァィ"

                "ゥェォッャュョヮヵヶ"; // Line-start (weak) prohibition characters

    var wwLeading="\\$([{｢‘“（〔［｛〈《「『【￥＄£"; // Line-end prohibition characters



	wwFollowing += wwFollowingWeak;



	var id; // Identifier

	var comp; // Corresponding front/back message layer





	// Variables marked with /*C*/ are automatically copied during assign.

	// Variables marked with /*S*/ are automatically copied during store/restore.

	// If you modify these variable names, delete them, or add new ones, you must

	// run this script as a perl script once again.

	// ( Processed by the perl script at the end )



	var layerType = ltAddAlpha; // Layer type

	/*CS*/var frameGraphic = ""; // Frame image filename

	/*CS*/var frameKey = clNone; // Frame image key

    var frameAnimCount;

    var frameAnimTime;

    /*CS*/var frameColor = 0x000000; // Frame color

	/*CS*/var frameOpacity = 128; // Frame opacity

	/*CS*/var marginL = 8; // Left margin

	/*CS*/var marginT = 8; // Top margin

	/*CS*/var marginR = 8; // Right margin

	/*CS*/var marginB = 8; // Bottom margin

	/*CS*/var marginRCh = 2; // Margin for kinsoku processing reserved at the right end (bottom end for vertical writing)

	var kinsokuCount;

	/*C*/var x;

	/*C*/var y; // Current display position

	/*C*/var relinexpos; // Final right (bottom for vertical writing) position for line breaking

	/*C*/var isLastLine; // Currently drawing the last line of the page

	/*C*/var indentxpos; // Indent left (top for vertical writing) position

	var links = [];  // Links

    var names = %[]; // Reference of links by name

    /*C*/var linkFilled; // Whether the link area image was filled

	/*C*/var numLinks = 0; // Number of links in the layer



	var lastLink = -1; // Last selected link number (for turning off highlight drawing)

	var _keyLink = -1; // Link number selected by keyboard (keyLink is property: shared with lastKeyLink)

	var lastKeyLink = -1; // Last selected link number by keyboard (for re-selection)

	property keyLink {

		getter { return _keyLink; }

		setter(v) {

			_keyLink = v;

			lastKeyLink = v if (v >= 0);

		}

	}

	var inLink = -1; // Whether a link is being drawn

	var highlightLayer; // Layer for highlighting links

	/*C*/var selProcessLock = false; // Flag to prevent link operation after process

	/*C*/var storedSelProcessLock = false; // State at the time of storeSelProcessLock



	/*CS*/var defaultLinkColor = 0x0080ff; // Default link color

	/*CS*/var defaultLinkOpacity = 64; // Default link opacity



	/*CS*/var defaultFontSize = 24; // Default font height

	/*CS*/var nameLayerFontSize = 0; // Font size of name layer (use defaultFontSize if 0)

	/*C*/var fontSize; // Font height

	/*C*/var _fontSize; // Temporary font height

	/*CS*/var defaultLineSize = 0; // Default line height

	/*C*/var reserveLineSize = 0; // 'Reserved' line height

	/*C*/var lineSize; // Line height

	/*CS*/var defaultRubySize = 10; // Default ruby height

	/*C*/var rubySize; // Ruby height

	/*C*/var _rubySize; // Temporary ruby height

	/*CS*/var defaultRubyOffset = -2; // Default ruby offset

	/*C*/var rubyOffset; // Ruby offset

	/*C*/var _rubyOffset; // Temporary ruby offset



	/*CS*/var defaultLineSpacing = 6; // Default line spacing

	/*C*/var lineSpacing; // Line spacing

	/*CS*/var defaultPitch = 0; // Default character pitch

	/*C*/var pitch; // Character pitch

	/*CS*/var defaultShadow = true; // Whether to add shadow by default

	/*C*/var shadow; // Whether to add shadow

	/*CS*/var defaultEdge = false; // Whether to use outline by default

	/*C*/var edge; // Whether to use outline

	/*CS*/var defaultShadowColor = 0x000000; // Default shadow color

	/*C*/var shadowColor; // Shadow color

	/*CS*/var defaultEdgeColor = 0x0080ff; // Default outline color

	/*C*/var edgeColor; // Outline color

	/*CS*/var defaultBold = true; // Whether to draw in bold by default

	/*C*/var bold; // Whether to draw in bold

	/*CS*/var defaultFace = "user"; // Default font

	/*C*/var userFace = "MS P Mincho"; // Font selected by user

	/*C*/var fontFace; // Font

	/*CS*/var defaultChColor = 0xffffff; // Default text color

	/*C*/var chColor; // Text color

	/*C*/var defaultAntialiased = true; // Whether to apply anti-aliasing by default

	/*C*/var antialiased; // Whether to apply anti-aliasing

	/*CS*/var vertical = false; // True when in vertical writing mode

	/*C*/var currentRuby = ""; // Ruby for the next character

	/*C*/var lastDrawnCh = ""; // Last character drawn



	/*CS*/var edgeExtent = 1; // Thickness of outline text

	/*CS*/var edgeEmphasis = 512; // Emphasis of outline text

	/*CS*/var shadowOffsetX = 2; // Shadow offset

	/*CS*/var shadowOffsetY = 2; // Shadow offset

	/*CS*/var shadowWidth   = 0; // Shadow blur intensity



	/*C*/var sizeChanged = false; // True when font size is changed



	/*C*/var nextClearFlag = false; // Whether to clear the layer on the next character when reaching bottom end



	var lineLayer; // Layer for line drawing

	var textLayer; // Layer holding text (optional) => See hasTextLayer property

	var chFadeLayer; // If using fade for character display => See hasChFadeLayer property

	/*C*/var redrawTextStates; // Info for text redrawing (optional) => See redrawTextEnabled

	/*C*/var lineLayerBase; // Baseline (Horizontal: underline pos / Vertical: center pos)

	/*C*/var lineLayerPos; // Character display position in lineLayer

	/*C*/var lineLayerLength; // Character width in lineLayer

	/*C*/var lineLayerOriginX; // Display offset X

	/*C*/var lineLayerOriginY; // Display offset Y

	/*C*/var lineLayerPadding = 4; // Padding pixels for top/bottom/left/right (for outline/shadow)

	var lineLayerLinks = []; // Links managed by lineLayer



	/*C*/var align=-1; // -1=Left/Top  0=Center   1=Right/Bottom

	/*CS*/var defaultAutoReturn = true; // Whether to auto line break by default

	/*C*/var autoReturn = true; // Whether to process auto line breaks/page breaks



	/*CS*/var lineBreakGlyph = "linebreak"; // Line break glyph name

	/*CS*/var lineBreakGlyphKey = clNone; // Line break glyph color key

    /*CS*/var lineBreakBaseLine = 0; // For baseline correction

    /*CS*/var pageBreakGlyph = "pagebreak"; // Page break glyph name

	/*CS*/var pageBreakGlyphKey = clNone; // Page break glyph color key

    /*CS*/var pageBreakBaseLine = 0; // For baseline correction

	/*CS*/var glyphFixedPosition = false; // Whether to display glyphs at fixed positions

	/*CS*/var glyphFixedLeft = 0; // That position

	/*CS*/var glyphFixedTop = 0;



	/*CS*/var glyphFixedSize   = false; // Fix glyph size

	/*CS*/var glyphFixedWidth  = 24;     // That width

	/*CS*/var glyphFixedHeight = 24;

    

	/*CS*/var draggable = false; // Whether message layer is draggable

	var dragging = false; // Whether currently dragging

	var dragOriginX, dragOriginY; // Coordinates being grabbed while dragging



	/*C*/var selClickLock = false; // Flag to prevent accidental operation from repeated clicks

	/*C*/var lastMouseX;

	/*C*/var lastMouseY; // Last mouse cursor position when showing links



    /*C*/var eventTransparent = true; // Event transparency

    

	var ml, mt, mw, mh; // Initial layer size (for config)



	var invisibleByUser = false; // Temporarily invisible by user

	var visibleBeforeUserInvisible  = false;



	var lastMouseDownX; // Last clicked X coordinate

	var lastMouseDownY; // Last clicked Y coordinate



	// Link types

    var ltNormal   = 1;

    var ltButton   = 2;

    var ltEdit     = 3;

    var ltCheckBox = 4;

    var ltSlider   = 5;

    var ltLayer    = 6;

    

    // Layer for name drawing

    var nameLayer;



    // Layer for face drawing

    var faceLayer;



    // System button layers

    var buttons = %[];

    var buttons_save = [];



    // For timeout processing

    var timeoutTimer;

    var timeoutTime;

    var timeoutStorage;

    var timeoutTarget;

    var timeoutExp;

    

    function clearTimeout() {

        stopTimeout();

        timeoutTime    = void;

        timeoutStorage = void;

        timeoutTarget  = void;

        timeoutExp     = void;

    }



    function timeoutHandler() {

        if (!selProcessLock) {

            Scripts.eval(timeoutExp) if timeoutExp != '';

            if (timeoutStorage != '' || timeoutTarget != '') {

                window.lockMessageLayerSelProcess(); // Lock selection

                window.process(timeoutStorage, timeoutTarget);

                clearTimeout();

            }

        }

    }



    function addTimeout(elm) {

        timeoutTime    = elm.time;

        timeoutStorage = elm.storage;

        timeoutTarget  = elm.target;

        timeoutExp = createSoundExpression(elm.exp, elm.se, elm.sebuf);

        setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

    }



    function stopTimeout() {

        if (timeoutTimer !== void) {

            invalidate timeoutTimer;

            timeoutTimer = void;

        }

    }

    

    function startTimeout() {

        if (timeoutTime > 0 && (timeoutStorage !== void || timeoutTarget !== void || timeoutExp !== void)) {

            timeoutTimer = new Timer(timeoutHandler, '');

            timeoutTimer.capacity = 1;

            timeoutTimer.interval = timeoutTime;

            timeoutTimer.enabled  = true;

        }

    }



    var clickExp;

    var clickStorage;

    var clickTarget;



    function clearClick() {

        clickStorage = void;

        clickTarget  = void;

        clickExp     = void;

    }



    function addClick(elm) {

        clickStorage = elm.storage;

        clickTarget  = elm.target;

        clickExp = createSoundExpression(elm.exp, elm.se, elm.sebuf);

        focusable = true; // Make it capable of receiving focus

        setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

        selClickLock = false;

    }



    function hasClick() {

        return clickExp !== void || clickStorage !== void || clickTarget !== void;

    }

    

    function processClick() {

        Scripts.eval(clickExp) if clickExp != '';

        if(clickStorage != '' || clickTarget != '') {

            window.lockMessageLayerSelProcess(); // Lock selection

            if (window.getKeyState(VK_RETURN) || window.getKeyState(VK_SPACE) || window.getKeyState(VK_CONTROL))

                window.hideMouseCursor();

            // Hide mouse cursor if operated by keyboard

            window.process(clickStorage, clickTarget);

            clearClick();

        }

        selClickLock = false;

    }

    

    var wheelExp;

    var wheelFunc;

    var wheelStorage;

    var wheelTarget;



    function clearWheel() {

        wheelStorage = void;

        wheelTarget  = void;

        wheelExp     = void;

        wheelFunc    = void;

    }



    function addWheel(elm) {

        wheelStorage = elm.storage;

        wheelTarget  = elm.target;

        wheelFunc    = elm.func;

        wheelExp = createSoundExpression(elm.exp, elm.se, elm.sebuf);

        focusable = true; // Make it capable of receiving focus

        setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

    }



    function hasWheel() {

        return wheelFunc !== void || wheelExp !== void || wheelStorage !== void || wheelTarget !== void;

    }

    

    function processWheel(shift, delta, x, y) {

        if (!selProcessLock) {

            Scripts.eval(wheelFunc)(shift, delta, x, y) if wheelFunc != void;

            Scripts.eval(wheelExp) if wheelExp != '';

            if(wheelStorage != '' || wheelTarget != '') {

                window.lockMessageLayerSelProcess(); // Lock selection

                window.process(wheelStorage, wheelTarget);

                clearWheel();

            }

        }

    }

    

    function MessageLayer(owner, parent, name, id, do_config)

	{

        left = 0;

        top  = 0;



        // MessageLayer constructor

		// owner : Owner KAG Window

        // parent : Parent Layer

        // name : Name

		// id : Identifier

		// left, top, width, height : Initial position

		// do_config : Whether to perform configuration

        super.AnimKAGLayer(...);



        _opacity = super.opacity;

        _visible = super.visible;

        

		this.id = id;

		this.name = name;



		imageModified = true;



		// Configuration

		if(do_config)

		{

			(MessageLayer_config incontextof this)();

			(MessageLayer_config_override incontextof this)()

				if typeof global.MessageLayer_config_override != "undefined";



			// Initial size is in mw mh

			setPos(ml, mt);

			setImageSize(mw, mh);

			setSize(mw, mh);

		}

		else

		{

			// If config is not performed

			// Size determined by defaults

			setPos(0, 0);

			setImageSize(parent.width, parent.height);

			setSize(parent.width, parent.height);

		}



		// Clear temporary config variables

		delete ml; delete mt; delete mw; delete mh;



		// Set layer type

		type = layerType;



		// Initialize hit detection

		hitType = htMask;

		hitThreshold = 0; // Mouse messages are fully opaque



		// Secure a floating layer for line drawing

		lineLayer = new MessageLineLayer(window, this);

		lineLayer.hitType = htMask;

		lineLayer.hitThreshold = 256; // Mouse messages are fully transparent

		lineLayer.face = dfAuto;

		lineLayer.type = layerType;

		lineLayer.name = "Floating message layer for line drawing";



		// Layer for highlighting links

		highlightLayer = new global.KAGLayer(window, this);

		highlightLayer.type = layerType;

		highlightLayer.face = dfAuto;

		highlightLayer.hitType = htProvince;

        highlightLayer.name = "Highlight layer";

        // Perform hit detection with area image



        _fadeTimer = new Timer(fadeHandler, '');

        _fadeTimer.capacity = 1;

        _fadeTimer.interval = 10;

        _fadeTimer.enabled  = false;

    }



    function clearSystemButtons() {

        foreach(buttons, function(name,value,dict) {

            invalidate value;

            delete dict[name];

        });

        buttons_save = [];

    }



    function initNameLayer() {

        if (nameLayer === void) {

            nameLayer = new NameLayer(this);

            nameLayer.type = layerType;

            nameLayer.name = name + ":Name";

            nameLayer.hitType = htProvince;

        }

		resetNameLayerFont();

    }



    function invalidateNameLayer() {

        if (nameLayer !== void) {

            invalidate nameLayer;

            nameLayer = void;

        }

    }



    function initFaceLayer() {

		if (faceLayer === void) {

			faceLayer = new FaceLayer(this);

			faceLayer.type = ltAlpha;

			faceLayer.name = name + ":Expression";

			faceLayer.hitType = htProvince;

		}

    }



	function swapFaceLayer() {

		if (comp !== void) {

			var tmp = comp.faceLayer;

			comp.faceLayer = faceLayer;

			faceLayer = tmp;

			comp.faceLayer.owner = comp;

			faceLayer.owner = this;

		}

	}

    

    function invalidateFaceLayer() {

		if (faceLayer !== void) {

			invalidate faceLayer;

			faceLayer = void;

        }

    }



    function finalize()

	{

        // Invalidate objects associated with links

		invalidateLinkObjects();

        invalidate highlightLayer;

        invalidate lineLayer;

        invalidate timeoutTimer if timeoutTimer !== void;

        invalidate textLayer if (textLayer !== void);



        super.finalize();

        

        clearSystemButtons();

        invalidate buttons;

        invalidate _fadeTimer;



        invalidateNameLayer();

        invalidateFaceLayer();

    }



	function setCompLayer(lay) { comp = lay; }



	function redrawFrame(force = false)

	{

		if(imageModified || force)

		{

			window.updateBeforeCh = 1;

			if(frameGraphic == "")

			{

				// If no frame image is specified

				face = dfAuto;

				if(type == ltAddAlpha)

				{

					fillRect(0, 0, imageWidth, imageHeight, (frameOpacity << 24) +

						((int)((((frameColor&0xff0000)>>16) * frameOpacity) / 255)<<16 ) +

						((int)((((frameColor&0x00ff00)>> 8) * frameOpacity) / 255)<< 8 ) +

						((int)((((frameColor&0x0000ff)    ) * frameOpacity) / 255)     ) );

				}

				else

				{

					fillRect(0, 0, imageWidth, imageHeight, (frameOpacity << 24) + frameColor);

				}

			}

			else

			{

                var anim = sf === void || sf.frameanimation === void || sf.frameanimation;

                loadImages(frameGraphic, frameKey, frameAnimCount, anim ? frameAnimTime : 0);

                setSizeToImageSize();



				// Apply frameOpacity

				if (frameOpacity < 255) {

					face = dfAlpha;

					colorRect(0, 0, imageWidth, imageHeight, 0, -255 + frameOpacity);

					face = dfAuto;

				}

			}



			face = dfProvince;

			colorRect(0, 0, imageWidth, imageHeight, 0); // Clear area as well

			face = dfAuto;

		}



		imageModified = false;

	}



    function clearLayer(all)

	{

		// Clear layer

		window.updateBeforeCh = 1;



		cancelDrag();



		redrawFrame();

		clearTextLayer();



		invalidateLinkObjects(); // Invalidate objects associated with links



		focusable = false;

        links.clear();

        

        numLinks = 0;

		inLink = -1;

		highlightLink(lastLink, false); // Turn off highlight

		highlightLayer.visible = false;

		lastLink = lastKeyLink = -1;

		keyLink = -1;

		linkFilled = false;

		lastDrawnCh = ""; // Last character drawn

		isLastLine = false; // Is last line

		selClickLock = true;

		lastMouseX = cursorX;

		lastMouseY = cursorY;

		initLineLayer();



        if (all) {

            faceLayer.visible = false if faceLayer !== void;

            nameLayer.visible = false if nameLayer !== void;

        }

    }



	function setPosition(elm)

	{

        // Stop animation for now

        animStop();

        

        // Set message layer options according to elm

		// The reason this tag is named position is a holdover from the

		// very early KAG days.

		left = elm.left if elm.left !== void;

		top = elm.top if elm.top !== void;

		imageWidth = elm.width if elm.width !== void;

		imageHeight = elm.height if elm.height !== void;

		setSizeToImageSize();



        frameGraphic = elm.frame if elm.frame !== void;

		frameOpacity = 255       if elm.frame !=  ""; // Reset frameOpacity when frameGraphic is specified (for compatibility)

        frameKey = elm.framekey if elm.framekey !== void;

        frameAnimCount = elm.frame !== void ? +elm.animcount : void; // Initialize if frame specified

        frameAnimTime  = elm.frame !== void ? +elm.animtime : void;



        frameColor = +elm.color if elm.color !== void;

		frameOpacity = +elm.opacity if elm.opacity !== void;

		imageModified = true; // To force clear the message layer

		marginL = +elm.marginl if elm.marginl !== void;

		marginT = +elm.margint if elm.margint !== void;

		marginR = +elm.marginr if elm.marginr !== void;

		marginB = +elm.marginb if elm.marginb !== void;

		vertical = +elm.vertical if elm.vertical !== void;

		draggable = +elm.draggable if elm.draggable !== void;

		visible = +elm.visible if elm.visible !== void;

        eventTransparent = +elm.transparent if elm.transparent !== void;

        

        // Name window

        if (elm.nameleft !== void) {

            initNameLayer();

            nameLayer.left     = +elm.nameleft   if elm.nameleft   !== void;

            nameLayer.top      = +elm.nametop    if elm.nametop    !== void;

            nameLayer.width    = +elm.namewidth  if elm.namewidth  !== void;

            nameLayer.height   = +elm.nameheight if elm.nameheight !== void;

            nameLayer.absolute = +elm.nameabsolute if elm.nameabsolute !== void;

            nameLayer.originMode = +elm.nameorigin if elm.nameorigin !== void;

			nameLayer.align    = +elm.namealign  if elm.namealign   !== void;

			nameLayer.valign   = +elm.namevalign if elm.namevalign  !== void;

        } else {

            invalidateNameLayer();

        }

        

        // Expression window

        if (elm.faceleft !== void) {

            initFaceLayer();

            faceLayer.left     = +elm.faceleft   if elm.faceleft   !== void;

            faceLayer.top      = +elm.facetop    if elm.facetop    !== void;

            faceLayer.width    = +elm.facewidth  if elm.facewidth  !== void;

            faceLayer.height   = +elm.faceheight if elm.faceheight !== void;

            faceLayer.absolute = +elm.faceabsolute if elm.faceabsolute !== void;

            faceLayer.originMode = +elm.faceorigin if elm.faceorigin !== void;

			faceLayer.noRelative = +elm.faceindepend if elm.faceindepend !== void;

        } else {

            invalidateFaceLayer();

        }

		textLayer.absolute = +elm.textabsolute if (elm.textabsolute !== void && hasTextLayer);

        

        // Clear message buttons

        clearSystemButtons();



        // Clear

        clear(true);



		// Added edge thickness specification

		edgeExtent = +elm.edgeextent if elm.edgeextent !== void;

	}



	function clear(all=false)

	{

		// Clear message layer

		clearLayer(all);



		// Display position to initial position

		if(vertical)

		{

			x = imageWidth - marginR;

			y = marginT;

		}

		else

		{

			x = marginL;

			y = marginT;

		}

		kinsokuCount = marginRCh;

		

		// Other resets

		indentxpos = 0;

		resetFont();

		resetStyle();

		decideSizeChange();

		initLineLayer();

		currentRuby = "";



        clearTimeout();

        clearClick();

        clearWheel();



		clearRedrawTextState();

    }



	function clear2(all=false)

	{

		// Clear message layer, but don't reset font.

		// Called when message reaches the bottom and page waits then clears the layer.



		clearLayer(all);



		// Display position to initial position

		if(vertical)

		{

			y = marginT + indentxpos;

			x = imageWidth - marginR;

		}

		else

		{

			y = marginT;

			x = marginL + indentxpos;

		}

		kinsokuCount = marginRCh;

		initLineLayer();



		clearRedrawTextState();

	}



    function resetNameLayerFont() {

        if (nameLayer !== void) {

            nameLayer.font.face   = userFace;

			nameLayer.font.height = nameLayerFontSize ? nameLayerFontSize : defaultFontSize;

			nameLayer.font.bold   = defaultBold;

        }

    }

    

	function resetFont()

	{

		storeRedrawTextState("resetFont");

		// Font reset

		sizeChanged = true;



		// Write back each default setting

		if(!vertical)

		{

			lineLayer.font.face = fontFace = defaultFace == 'user' ? userFace : defaultFace;

			lineLayer.font.angle = 0;

        }

		else

		{

			lineLayer.font.face = '@' + (fontFace = defaultFace == 'user' ? userFace : defaultFace);

			lineLayer.font.angle = 2700;

        }

        

		lineLayer.font.bold = bold = defaultBold;

		lineLayer.font.italic=false;

		_fontSize = defaultFontSize;

		antialiased = defaultAntialiased;



		chColor = defaultChColor;

		_rubySize = defaultRubySize;

		_rubyOffset = defaultRubyOffset;

		shadow = defaultShadow;

		edge = defaultEdge;

		shadowColor = defaultShadowColor;

		edgeColor = defaultEdgeColor;



		// Calculate line break position

		if(!vertical)

			relinexpos = imageWidth - marginR - marginRCh * _fontSize;

        else

            relinexpos = imageHeight - marginB - marginRCh * _fontSize;



		resetNameLayerFont();

	}



	function setFont(elm)

	{

		storeRedrawTextState("setFont", elm);

		// Font settings

		sizeChanged = true;



		if(!vertical)

		{

			var elmface = elm.face;

			if(elmface == 'default')

			{

                lineLayer.font.angle = 0;

                lineLayer.font.face = fontFace =  defaultFace;

			}

			else if(elmface == 'user')

			{

				lineLayer.font.angle = 0;

				lineLayer.font.face = fontFace = userFace;

			}

			else if(elmface !== void)

			{

				lineLayer.font.angle = 0;

				lineLayer.font.face = fontFace = elmface;

			}

		}

		else

		{

			var elmface = elm.face;

			if(elmface == 'default')

			{

				var f = '@' + (fontFace = defaultFace);

				lineLayer.font.angle = 2700;

				lineLayer.font.face = f;

			}

			else if(elmface == 'user')

			{

				var f = '@' + (fontFace = userFace);

				lineLayer.font.angle = 2700;

				lineLayer.font.face = f;

			}

			else if(elmface !== void)

			{

				var f = '@' + (fontFace = elmface);

				lineLayer.font.angle = 2700;

				lineLayer.font.face = f;

			}

		}



        if(elm.antialiased == 'default')

			antialiased = defaultAntialiased;

		else if(elm.antialiased !== void)

			antialiased = +elm.antialiased;



		if(elm.bold == 'default')

			lineLayer.font.bold = defaultBold;

		else if(elm.bold !== void)

			lineLayer.font.bold = +elm.bold;



		if(elm.italic == 'default')

			lineLayer.font.italic = false;

		else if(elm.italic !== void)

			lineLayer.font.italic = +elm.italic;



		if(elm.size == 'default')

			_fontSize = defaultFontSize;

		else if(elm.size !== void)

			_fontSize = +elm.size;

		if (!_fontSize) throw new Exception("Invalid font size (verify spelling errors like 'default'): "+elm.size);

		

		if(elm.color == 'default')

			chColor = defaultChColor;

		else if(elm.color !== void)

			chColor = +elm.color;



		if(elm.rubysize == 'default')

			_rubySize = defaultRubySize;

		else if(elm.rubysize !== void)

			_rubySize = +elm.rubysize;



		if(elm.rubyoffset == 'default')

			_rubyOffset = defaultRubyOffset;

		else if(elm.rubyoffset !== void)

			_rubyOffset = +elm.rubyoffset;



		if(elm.shadow == 'default')

			shadow = defaultShadow;

		else if(elm.shadow !== void)

			shadow = +elm.shadow;



		if(elm.shadowcolor == 'default')

			shadowColor = defaultShadowColor;

		else if(elm.shadowcolor !== void)

			shadowColor = +elm.shadowcolor;



		if(elm.edge == 'default')

			edge = defaultEdge;

		else if(elm.edge !== void)

			edge = +elm.edge;



		if(elm.edgecolor == 'default')

			edgeColor = defaultEdgeColor;

		else if(elm.edgecolor !== void)

			edgeColor = +elm.edgecolor;



		if(!vertical)

			relinexpos = int(imageWidth-marginR-marginRCh*_fontSize);

		else

			relinexpos = int(imageHeight-marginB-marginRCh*_fontSize);

    }



	function setDefaultFont(elm)

	{

		storeRedrawTextState("setDefaultFont", elm);

		// Set default font

		defaultFace = elm.face if elm.face !== void;

		defaultAntialiased = +elm.antialiased if elm.antialiased !== void;

		defaultBold = +elm.bold if elm.bold !== void;

		defaultFontSize = +elm.size if elm.size !== void;

		defaultChColor = +elm.color if elm.color !== void;

		defaultRubySize = +elm.rubysize if elm.rubysize !== void;

		defaultRubyOffset = +elm.rubyoffset if elm.rubyoffset !== void;

		defaultShadow = +elm.shadow if elm.shadow !== void;

		defaultShadowColor = +elm.shadowcolor if elm.shadowcolor !== void;

		defaultEdge = +elm.edge if elm.edge !== void;

		defaultEdgeColor = +elm.edgecolor if elm.edgecolor !== void;

	}



	function resetStyle()

	{

		storeRedrawTextState("resetStyle");

		// Style reset

		reserveLineSize = defaultLineSize;

		lineSpacing = defaultLineSpacing;

		pitch = defaultPitch;

		resetLineSize();

		align = -1;

		autoReturn = defaultAutoReturn;

		adjustAlign();

	}



	function setStyle(elm)

	{

		storeRedrawTextState("setStyle", elm);

		// Style settings

		if(elm.linespacing == 'default')

			lineSpacing = defaultLineSpacing;

		else if(elm.linespacing !== void)

			lineSpacing = +elm.linespacing;



		if(elm.pitch == 'default')

			pitch = defaultPitch;

		else if(elm.pitch !== void)

			pitch = +elm.pitch;



		if(elm.linesize == 'default')

		{

			reserveLineSize = defaultLineSize;

		}

		else if(elm.linesize !== void)

		{

			reserveLineSize = +elm.linesize;

			resetLineSize();

			sizeChanged  =true;

		}



		if(elm.align == 'default')

		{

			fixLineLayer();

			align = -1;

			adjustAlign();

		}

		else if(elm.align !== void)

		{

			fixLineLayer();

			if(elm.align == 'left' || elm.align == 'top')

				align = -1;

			else if(elm.align == 'center')

				align = 0;

			else if(elm.align == 'right' || elm.align == 'bottom')

				align = 1;

			adjustAlign();

		}

		

		if(elm.autoreturn == 'default')

			autoReturn = defaultAutoReturn;

		else if(elm.autoreturn !== void)

			autoReturn = +elm.autoreturn;

	}



	function setDefaultStyle(elm)

	{

		storeRedrawTextState("setDefaultStyle", elm);

		// Set default styles

		defaultLineSpacing = +elm.linespacing if elm.linespacing !== void;

		defaultPitch = +elm.pitch if elm.pitch !== void;

		defaultLineSize = +elm.linesize if elm.linesize !== void;

		defaultAutoReturn = +elm.autoreturn if elm.autoreturn !== void;

	}





	function resetLineSize()

	{

		// Line size reset

		lineSize = reserveLineSize > fontSize ? reserveLineSize : fontSize;

	}



	function decideSizeChange()

	{

		// Finalize font/style info that was tentatively changed

		if(!sizeChanged) return;

		lineLayer.font.height = - _fontSize;

		fontSize = _fontSize;

		rubySize = _rubySize;

		rubyOffset = _rubyOffset;

		sizeChanged = false;

	}



	function getLineLayerBaseLine()

	{

		// Calculate and return baseline for character display

		// Bottom end for horizontal writing,

		// Center line for vertical writing.

		if(!vertical)

			return -getLineLayerTopOffset() + lineSpacing + lineSize;

		else

			// Vertical

			// Center line (position from layer left edge)

			return lineLayerPadding + (lineSize>>1);

	}



	function initLineLayer()

	{

		// Initialize lineLayer

		var ll = lineLayer;

		resetLineSize();

		lineLayerLinks.count = 0;

		lineLayerOriginX = x;

		lineLayerOriginY = y;

		if(!vertical)

			ll.imageWidth = imageWidth + lineLayerPadding*2;

		else

			ll.imageHeight = imageHeight + lineLayerPadding*2;

		ll.setSizeToImageSize();

		changeLineSize(/*forceresize=*/true);

		lineLayerLength = 0;

		lineLayerPos = lineLayerPadding;

		ll.visible = false;

		ll.face = dfAuto;

		var lliw = ll.imageWidth;

		var llih = ll.imageHeight;

		ll.fillRect(0, 0, lliw, llih, 0); // Fully transparent

		ll.face = dfProvince;

		ll.fillRect(0, 0, lliw, llih, 0); // Clear area

		ll.face = dfAuto;



		resetChFadeLayer(true);

	}



	// Property for getting/setting presence of text layer (special use for calling redrawFrame directly)

	// * Setting this in MessageLayer_config is problematic; set it individually in AfterInit instead.

	property hasTextLayer {

		getter { return textLayer !== void; }

		setter(v) {

			if        ( v && textLayer === void) {

				textLayer = new MessageTextLayer(this);

				with (textLayer) {

					.hitType = htMask;

					.hitThreshold = 256; // Fully transparent to mouse

					.type = layerType;

					.name = name + ":Text";



					setSizeToImageSize(); // Synchronize size

					clearTextLayer();

					.visible = true;

				}

				if (lineLayer !== void) {

					lineLayer.parent = textLayer;

				}

			} else if (!v && textLayer !== void) {

				if (lineLayer !== void) {

					lineLayer.parent = this;

					lineLayer.order = 0;

				}

				invalidate textLayer;

				textLayer = void;

			}

		}

	}

	// Clear text layer

	function clearTextLayer() {

		if (hasTextLayer) with (textLayer) {

			.face = dfAuto;

			.fillRect( 0, 0, .imageWidth, .imageHeight, 0);

			.face = dfProvince;

			.colorRect(0, 0, .imageWidth, .imageHeight, 0); // Clear area as well

			.face = dfAuto;

		}

	}

	function setSizeToImageSize() {

		super.setSizeToImageSize();

		// Synchronize textLayer size

		if (hasTextLayer) with (textLayer) {

			.setImageSize(width, height);

			.setSizeToImageSize();

		}

		subLayersRePosition();

	}



	// Text redraw mechanism on/off

	var     _redrawTextEnabled = false;

	property redrawTextEnabled {

		getter { return _redrawTextEnabled &&     redrawTextStates !==    void;      }

		setter(v) {     _redrawTextEnabled = !!v; redrawTextStates = !v ? void : []; }

	}

	// Redraw text

	function redrawText() {

		if (!redrawTextEnabled) return;

		_redrawTextEnabled = false;

		for (var i = 0, cnt = redrawTextStates.count; i < cnt; i++) {

			var arr = [], orig = redrawTextStates[i];

			arr.assign(orig);

			arr.erase(0);

			this[orig[0]](arr*);

		}

		_redrawTextEnabled = true;

		window.setMenuAccessibleAll();

	}

	// Save text redraw info

	function storeRedrawTextState(arr*) {

		if (!redrawTextEnabled) return;

		var store = [];

		store.assignStruct(arr);

		redrawTextStates.add(store);

	}

	// Initialize text redraw info

	function clearRedrawTextState() {

		if (!redrawTextEnabled) return;

		redrawTextStates.clear();

		storeRedrawTextState("clear");

		var dic = store();

		dic.noFaceRestore = true;

		storeRedrawTextState("restore", dic);

	}



	function fixLineLayer()

	{

		stopChFade();

		// Determine lineLayer at the current display position

		var ll = lineLayer;

		if(ll.visible == false) return;



		var llox = lineLayerOriginX + getLineLayerLeftOffset();

		var lloy = lineLayerOriginY + getLineLayerTopOffset();



		var target =   hasTextLayer ? textLayer : this; // Drawing destination

		var cnt    = (!hasTextLayer && animCount > 0) ? animCount : 1; // Copy count



		// Draw lineLayer

		target.face = dfAuto;

		for (var j=0;j<cnt;j++) {

			target.operateRect(

				llox,

				lloy + height * j,

				ll, 0, 0, ll.imageWidth, ll.imageHeight);

		}



		// Set hyperlink areas

		target.face = dfProvince;

		var i;

		var lll = lineLayerLinks;

		var lllcount = lll.count;

		for(i = 0; i<lllcount; i++)

		{

			var lll_i = lineLayerLinks[i];

			var n = lll_i.number;

			var l = lll_i.line;

			var linkn = links[n];

			var x = linkn.x[l] += llox;

			var y = linkn.y[l] += lloy;

			var w = linkn.w[l];

			var h = linkn.h[l];

			linkn.fixed[l] = true; // Fixed



			for (var j=0;j<cnt;j++) {

				target.colorRect(x, y + height * j, w, h, n+1); // Fill the corresponding part of this layer

			}

		}



		target.face = dfAuto;

		ll.visible = false;

	}





	function changeLineSize(forceresize = false)

	{

		// Called when line size changes to resize the line drawing layer.



		if(inLink!=-1) endLinkLine();

		decideSizeChange();



		var newlinesize = lineSize;

		if(fontSize>lineSize) newlinesize = fontSize; // Expansion



		var newlinelayersize = newlinesize + lineSpacing;

		if(rubySize + rubyOffset > lineSpacing)

		{

			// Ruby overlaps with the previous line

			newlinelayersize += rubySize+rubyOffset - lineSpacing;

		}



		newlinelayersize += lineLayerPadding*2; // Margin for outline/shadow drawing

		if(!vertical)

		{

			// Horizontal

			if(forceresize || lineLayer.imageHeight<newlinelayersize)

			{

				// Line expansion

				lineSize = newlinesize;

				var oldsize = lineLayer.imageHeight;

				lineLayer.imageHeight = newlinelayersize;

				lineLayer.setSizeToImageSize();

				lineLayerBase = getLineLayerBaseLine();

				// Content movement

				if(!forceresize)

				{

					var d = lineLayer.imageHeight - oldsize;

					lineLayer.face = dfAuto;

					lineLayer.copyRect(0, d, lineLayer,

						0, 0, lineLayer.imageWidth, oldsize);

					lineLayer.fillRect(0, 0, lineLayer.imageWidth, d, 0);



					lineLayer.face = dfProvince;

					lineLayer.copyRect(0, d, lineLayer,

						0, 0, lineLayer.imageWidth, oldsize);

					lineLayer.colorRect(0, 0, lineLayer.imageWidth, d, 0);

					lineLayer.face = dfAuto;

				}

				var i;

				for(i = 0; i<lineLayerLinks.count; i++)

				{

					var n = lineLayerLinks[i].number;

					var l = lineLayerLinks[i].line;

					links[n].y[l] += lineLayer.imageHeight - oldsize;

				}

				// Move position 

                lineLayer.setPos(lineLayerOriginX + getLineLayerLeftOffset(),

							lineLayerOriginY + getLineLayerTopOffset());

			}

		}

		else

		{

			// Vertical

			if(forceresize || lineLayer.imageWidth < newlinelayersize)

			{

				// Line expansion

				lineSize = newlinesize;

				var oldbase = lineLayerBase;

				var oldsize = lineLayer.imageWidth;

				lineLayer.imageWidth = newlinelayersize;

				lineLayer.setSizeToImageSize();

				lineLayerBase = getLineLayerBaseLine();

				// Content movement

				if(!forceresize)

				{

					lineLayer.face = dfAuto;

					// Move displayed content using oldbaseline, lineLayerBase

					lineLayer.copyRect(

						lineLayerBase - oldbase, 0,

						lineLayer,

						0,0,lineLayer.imageWidth, lineLayer.imageHeight);

					// Clear left and right ends

					lineLayer.fillRect(0, 0,

						lineLayerBase - oldbase, lineLayer.imageHeight, 0);

					lineLayer.fillRect(

						lineLayerBase - oldbase+oldsize, 0,

						lineLayer.imageWidth - (lineLayerBase - oldbase + oldsize),

						lineLayer.imageHeight, 0);



					lineLayer.face = dfProvince;

					lineLayer.copyRect(

						lineLayerBase - oldbase, 0,

						lineLayer,

						0, 0, lineLayer.imageWidth, lineLayer.imageHeight);

					lineLayer.colorRect(0, 0,

						lineLayerBase - oldbase, lineLayer.imageHeight, 0);

					lineLayer.colorRect(

						lineLayerBase - oldbase+oldsize, 0,

						lineLayer.imageWidth - (lineLayerBase - oldbase + oldsize),

						lineLayer.imageHeight, 0);

					lineLayer.face = dfAuto;

				}

				var i;

				for(i = 0; i < lineLayerLinks.count; i++)

				{

					var n = lineLayerLinks[i].number;

					var l = lineLayerLinks[i].line;

					links[n].x[l] += lineLayerBase - oldbase;

				}

				// Move position 

				lineLayer.setPos(lineLayerOriginX + getLineLayerLeftOffset(),

							lineLayerOriginY + getLineLayerTopOffset());

			}

		}

		resetChFadeLayer();

	}



	function getLineLayerLeftOffset()

	{

		// Get left offset within the line drawing layer

		if(!vertical)

		{

			if(align == -1)

				return -lineLayerPadding;

			else if(align == 0)

				return ((imageWidth - marginR - marginL - lineLayerLength)>>1) - lineLayerPadding;

			else if(align == 1)

				return imageWidth - marginR - marginL - lineLayerLength - lineLayerPadding;

		}

		else

		{

			return -lineSize - lineSpacing - lineLayerPadding;

		}

	}



	function getLineLayerTopOffset()

	{

		// Get top offset within the line drawing layer

		if(!vertical)

		{

			return -(lineLayer.imageHeight - lineLayerPadding - lineSize - lineSpacing);

		}

		else

		{

			if(align == -1)

				return -lineLayerPadding;

			else if(align == 0)

				return ((imageHeight - marginB - marginT - lineLayerLength)>>1) - lineLayerPadding;

			else if(align == 1)

				return imageHeight - marginB - marginT - lineLayerLength - lineLayerPadding;

			return -lineLayerPadding;

		}

	}



	function adjustAlign()

	{

		lineLayer.setPos(lineLayerOriginX + getLineLayerLeftOffset(),

			lineLayerOriginY + getLineLayerTopOffset());

	}





	function reline()

	{

		// Line break

		// Returns true if it exceeds page, false if it can break within the page.

		var condition;

		if(vertical)

		{

			condition= lineLayerOriginX + getLineLayerLeftOffset() - lineSpacing -

				lineSize <= marginL;

		}

		else

		{

			condition= lineLayerBase + lineLayerOriginY + getLineLayerTopOffset() +

				 lineSize >= imageHeight-marginB;

		}



		if(condition)

		{

			// Exceeds page!

			return true;

		}

		else

		{

			if(inLink != -1) endLinkLine();



			decideSizeChange();



			fixLineLayer();



			if(vertical)

			{

				y = marginT + indentxpos;

				x -= lineSize + lineSpacing;

			}

			else

			{

				y += lineSize + lineSpacing;

				x = marginL + indentxpos;

			}

			kinsokuCount = marginRCh;



			var condition;

			if(vertical)

				condition= x - lineSize*2 <= marginL;

			else

				condition= y + lineSize*2 >= imageHeight-marginB;



			if(condition)

			{

				// Page's last line

				isLastLine=true;

			}



			initLineLayer();



//			if(inLink!=-1) beginLinkLine();

		}

		return false;

	}



	// Compatibility for character display fading

	// * Setting this in MessageLayer_config is problematic; set it individually in AfterInit instead.

	property hasChFadeLayer {

		getter { return chFadeLayer !== void; }

		setter(v) {

			if        ( v && chFadeLayer === void) {

				chFadeLayer = new global.KAGLayer(window, lineLayer);

				with (chFadeLayer) {

					.hitType = htMask;

					.hitThreshold = 256; // Fully transparent to mouse

					.type = layerType;

					.name = name + ":Char Fade";

					.setPos(0, 0);

					.visible = true;

				}

				resetChFadeLayer();

			} else if (!v && chFadeLayer !== void) {

				invalidate chFadeLayer;

				chFadeLayer = void;

			}

		}

	}

	var _chFadeLayerAction;

	function startChFade(time) {

		if (!hasChFadeLayer) return;

		var act = _chFadeLayerAction;

		if (act === void)

			act = _chFadeLayerAction = %[ opacity:%[ handler:MoveAction, start:0, value:255, time:0 ] ];

		with (act)         .opacity.time = time;

		with (chFadeLayer) .opacity      = 0;

		window.beginAction(chFadeLayer, act, fixChFadeLayer);

	}

	function stopChFade() { window.stopAction(chFadeLayer) if (hasChFadeLayer); }

	function fixChFadeLayer() {

		if (hasChFadeLayer) with (chFadeLayer) {

			lineLayer.operateRect(0, 0, chFadeLayer, 0, 0, .imageWidth, .imageHeight);

			.fillRect(0, 0, .imageWidth, .imageHeight, 0);

		}

	}

	function resetChFadeLayer(init) {

		if (hasChFadeLayer) with (chFadeLayer) {

			if (init) stopChFade();

			var ll = lineLayer, lf = ll.font;

			.setImageSize(ll.imageWidth, ll.imageHeight);

			.setSizeToImageSize();

			with (.font) {

				.angle  = lf.angle;

				.bold   = lf.bold;

				.face   = lf.face;

				.height = lf.height;

				.italic = lf.italic;

			}

		}

	}



	function processCh(ch, steptime = 0)

	{

		stopChFade();

		storeRedrawTextState("processCh", ch, 0);

		// Draws character ch.

		// Returns true if a line break occurs and exceeds page end.

		// Otherwise returns false.

		var vert = vertical, relined = false;



		if((vert ?  y >= relinexpos  : x >= relinexpos ) && autoReturn)

		{

			relined = true;

			if (kinsokuCount <= 0) {

				if(reline()) return autoReturn;

			} else if(((lastDrawnCh=="" || wwLeading.indexOf(lastDrawnCh)==-1) &&

				wwFollowing.indexOf(ch)==-1) ||

				(lastDrawnCh!="" && wwFollowingWeak.indexOf(lastDrawnCh)!=-1 &&

					wwFollowingWeak.indexOf(ch)!=-1))

			{

				// Last drawn char is not an line-end prohibition char, 

				// and current char is not a line-start prohibition char,

				// or weak kinsoku characters are not consecutive.

				if(reline()) return autoReturn;

			}

			else if(vert ? ( y>imageHeight ) : (x>imageWidth))

			{

				// If the char to be drawn is not a strong prohibition char,

				// but definitely exceeds the right edge.

				// (In this case, margin is not considered)

				if(reline()) return autoReturn;

			} else {

				kinsokuCount--;

				relined = false;

			}

		}



		changeLineSize() if sizeChanged;



		var inlink = inLink != -1;



		beginLinkLine() if inlink;



		var ll = (steptime > 0 && hasChFadeLayer) ? chFadeLayer : lineLayer;

		var llfont = ll.font;



		var cw = llfont.getTextWidth(ch);



		var dx , dy;



		if(vert)

			dx = int(lineLayerBase+(fontSize>>1)), dy = int(lineLayerPos);

		else

			dx = int(lineLayerPos), dy = int(lineLayerBase-fontSize);





		drawTextToLayer(ll, dx, dy, ch, chColor);



		if(currentRuby != "")

		{

			// Ruby exists

			var cw = llfont.getTextWidth(ch);

			var orgsize = llfont.height;

			llfont.height = rubySize;

			var rw = llfont.getTextWidth(currentRuby);

			var rx,ry;

			if(!vert)

			{

				rx = int(dx + (cw>>1) - (rw>>1));

				ry = int(dy - rubySize - rubyOffset);

			}

			else

			{

				rx = int(dx + rubySize + rubyOffset);

				ry = int(dy + (cw>>1) - (rw>>1));

			}



			drawTextToLayer(ll, rx, ry, currentRuby, chColor);



			llfont.height = orgsize;

			currentRuby = '';

		}



		ll = lineLayer;

		ll.visible = true;

		startChFade(steptime) if (steptime > 0);



		if(inlink)

		{

			// Hyperlinking

			ll.face = dfProvince;

			if(!vert)

				ll.fillRect(lineLayerPos, lineLayerBase - fontSize,

					cw, fontSize, numLinks + 1);

			else

				ll.fillRect(lineLayerBase - (fontSize>>1), lineLayerPos,

					fontSize, cw, numLinks + 1);



			// Fill area image as well

			ll.face = dfAuto;

			linkFilled = true;

		}



		cw += pitch;



		if(vert) y += cw; else x += cw;



		lineLayerPos += cw;

		lineLayerLength += cw;



		lastDrawnCh = ch;



		adjustAlign() if(align >= 0);



		return relined ? false : void; // [XXX]

	}

	function drawTextToLayer(lay, x, y, text, color) {

		var win = lay.window;

		if (typeof   win.bitmapFont == "Object" && win.bitmapFont) {

			var dt = win.bitmapFont.drawTextToLayer;

			// Force drawing using bitmap font specification

			dt(lay, x+shadowOffsetX, y+shadowOffsetY, text, shadowColor) if (shadow);

			dt(lay, x, y, text, color);

			return;

		}

		var dt = lay.drawText;

		if (!vertical && edge && antialiased && typeof lay.drawPathString != "undefined") {

			// layerExDraw extension

			var tag = "__gdiplusfontapp";

			lay[tag] = new global.MessageLayer.GdiPlusFontApp() if (typeof lay[tag] == "undefined");

			lay[tag].drawText(this, lay, x, y, text, color);

		}

		else if(edge)   dt(x, y, text, color, 255, antialiased, edgeEmphasis, edgeColor, edgeExtent, 0, 0);

		else if(shadow) dt(x, y, text, color, 255, antialiased, 255, shadowColor, shadowWidth, shadowOffsetX, shadowOffsetY);

		else            dt(x, y, text, color, 255, antialiased);

	}

	class GdiPlusFontApp {

		var gp = global.GdiPlus;

		var padding = 0;

		var appCache = %[], fontCache = %[];

		var appTags = [ "edge",   "edgeColor",   "edgeExtent",

						"shadow", "shadowColor", "shadowWidth",

						"shadowOffsetX", "shadowOffsetY" ];

		var fontTags = [ "height", "bold", "italic", "strikeout", "underline" ];

		var penCaps = %[ /**/dashCap: gp.DashCapFlat,

						 /**/startCap:gp.LineCapRound,

						 /**/endCap:  gp.LineCapRound,

						 /**/lineJoin:gp.LineJoinRound ];

		var app, font, face, color;

		function GdiPlusFontApp() { app  = new gp.Appearance(); }

		function finalize()       { invalidate app; }

		function getcolor(col, al=(col>>24)&0xFF) { return (al > 0) ? col : (0xFF000000 | col & 0x00FFFFFF);  }

		function getpen(ext) { var ret = %[ width:ext ]; (Dictionary.assign incontextof ret)(penCaps, false); return ret; }

		function check(base, tag) {

			var list = this[tag + "Tags"], dic = this[tag + "Cache"];

			for (var i = list.count-1; i >= 0; i--) if ((tag = list[i]) != "" && dic[tag] !== base[tag]) return true;

		}

		function update(base, tag) {

			var list = this[tag + "Tags"], dic = this[tag + "Cache"];

			for (var i = list.count-1; i >= 0; i--) if ((tag = list[i]) != "") dic[tag] = base[tag];

		}

		function updateApp(base, col) { with (base) {

			if (color !== col || check(base, "app")) {

				color  =  col,  update(base, "app");

				app.clear();

				padding = .edge ? .edgeExtent : 0;

				if (.shadow) {

					app.addPen(  getcolor(.shadowColor), getpen(.shadowWidth), .shadowOffsetX, .shadowOffsetY) if (.shadowWidth > 0);

					app.addBrush(getcolor(.shadowColor),                       .shadowOffsetX, .shadowOffsetY);

					var ofs = Math.max(Math.abs(.shadowOffsetX), Math.abs(.shadowOffsetY));

					padding = Math.max(padding, ofs + .shadowWidth);

				}

				app.addPen(      getcolor(.edgeColor  ), getpen(.edgeExtent),  0, 0) if (.edge);

				app.addBrush(    getcolor( col        ),                       0, 0);

				padding+=4; //[XXX] Countermeasure for bottom-aligned fonts (can it be measured?)

			}

		} }

		function updateFont(lf) { with (lf) {

			var noFont   = (font === void);

			var faceChgd = (face !== .face);

			if (noFont  || faceChgd || check(lf, "font")) {

				face =    .face,      update(lf, "font");

				var style = .bold ? gp.FontStyleBold : gp.FontStyleRegular;

				style |= gp.FontStyleItalic    if (.italic);

				style |= gp.FontStyleUnderline if (.underline);

				style |= gp.FontStyleStrikeout if (.strikeout);

				if (noFont) {

					font = new gp.Font(face, .height, style);

				} else {

					font.familyName = face if (faceChgd);

					font.emSize = .height;

					font.style  =  style;

				}

			}

		} }

		function drawText(base, lay, x, y, text, color) {

			if (text == "") return;

			var len = text.length;

			var lf  = lay.font;

			var gtw = lf.getTextWidth;

			var ds  = lay.drawPathString;

			updateApp(base, color);

			updateFont(lf);

			var fw = 0, fh = lf.height, sx = x;

			if (typeof lay.measureStringInternal == "Object") {

				var ms=lay.measureStringInternal;

				for (var i = 0; i < len; i++, x+=fw) {

					var ch = text.charAt(i);

					with (ms(font, ch)) ds(font, app, x-.left, y-.top, ch);

					fw = gtw(ch);

				}

			} else {

				for (var i = 0; i < len; i++, x+=fw) {

					var ch = text.charAt(i);

					ds(font, app, x-(fh*100/600)-((fw=gtw(ch))*10/600), y, ch);

					fw = gtw(ch);

				}

			}

			// Manually update the update area of layerExDraw as it might be narrow.

			lay.update(sx-padding, y-padding, (x-sx)+padding*2, fh+padding*2);

		}

	}



	function putGraph(storage, key, ischar)

	{

		// Draw image storage.



		// Prepare temporary layer

		var lay = window.temporaryLayer;



		lay.type = ltTransparent;

		lay.face = dfAuto;

		lay.loadImages(storage, key); // Load image

		var lw, lh;

		lw = lay.imageWidth;

		lh = lay.imageHeight;



		var cw;

		if(vertical)

		{

			if(lw > lineSize) lineSize = lw; // Expand

			cw = lh;

		}

		else

		{

			if(lh > lineSize) lineSize = lh; // Expand

			cw = lw;

		}



		changeLineSize();



		if(inLink != -1) beginLinkLine();



		var repage = false, relined = false;



		if(autoReturn)

		{

			// Reached line break position?

			if(vertical ? ( y > relinexpos ) : (x > relinexpos) )

			{

				relined = true;

				repage = reline();

			}

		}



		if(repage) return true; // Character is not drawn





		// Drawing

		var cx,cy;

		if(vertical)

		{

			cx = lineLayerBase - (lw>>1);

			cy = lineLayerPos;

		}

		else

		{

			cx = lineLayerPos;

			cy = lineLayerBase - lh;

		}



		if(ischar && (shadow || edge) )

		{

			lay.face = dfOpaque;

			lay.holdAlpha = true;

				// Fill main part with shadow/outline color



			if(edge)

			{

				// Outline

				lay.fillRect(0, 0, lw, lh, edgeColor);

				lineLayer.operateRect(cx+1, cy, lay, 0, 0, lw, lh);

				lineLayer.operateRect(cx, cy+1, lay, 0, 0, lw, lh);

				lineLayer.operateRect(cx-1, cy, lay, 0, 0, lw, lh);

				lineLayer.operateRect(cx, cy-1, lay, 0, 0, lw, lh);

			}

			else if(shadow)

			{

				// Shadow

				lay.fillRect(0, 0, lw, lh, shadowColor);

				lineLayer.operateRect(cx+shadowOffsetX, cy+shadowOffsetY, lay, 0, 0, lw, lh);

			}



		}



		if(ischar)

		{

			lay.face = dfOpaque;

			lay.holdAlpha = true;

			lay.fillRect(0, 0, lw, lh, chColor);

				// Fill main part with text color

		}



		lineLayer.operateRect(cx, cy, lay, 0, 0, lw, lh); // Drawing



		// End drawing

		lastDrawnCh="";



		if(inLink!=-1)

		{

			// Hyperlinking

			lineLayer.face = dfProvince;

			if(vertical)

				lineLayer.fillRect(lineLayerBase - (fontSize>>1), lineLayerPos,

					fontSize, cw, numLinks+1);

			else

				lineLayer.fillRect(lineLayerPos, lineLayerBase - fontSize,

					cw, fontSize, numLinks+1);

			face = dfAuto;

			lineLayer.face = dfBoth;

			// Fill area image as well

			linkFilled=true;

		}



		if(vertical) y+=cw; else x+=cw;



		lineLayerPos += cw;

		lineLayerLength += cw;



		lineLayer.visible = true;



		if(align >= 0) adjustAlign();



		return relined ? false : void; // [XXX]

	}



	function putHorizonCh(text, expand = false)

	{

		stopChFade();

		storeRedrawTextState("putHorizonCh", text, expand);

		// Draws Tate-chu-yoko (Horizontal text in vertical line)

		if(!vertical) throw new Exception("Cannot be used unless in vertical writing mode");



		// Reset font settings

		var ll = lineLayer;

		var lf = ll.font;

		var orgfont = lf.face;

		var organgle = lf.angle;

		lf.face = orgfont.substring(1); // Remove leading @ mark

		lf.angle = 0;



		// Get width of text to be drawn

		var cw = lf.getTextWidth(text);

		var ch = fontSize;



		// Expansion of linesize

		if(expand)

		{

			if(cw > lineSize) lineSize = cw; // Expand

			changeLineSize();

		}



		// Start link if currently in a link

		if(inLink != -1) beginLinkLine();



		// Line break/Page break processing

		var repage = false;

		if(autoReturn)

		{

			// Reached line break position?

			if(y > relinexpos) repage = reline();

		}

		if(repage)

		{

			// Restore font before returning

			lf.face = orgfont;

			lf.angle = organgle;

			return true; // Character is not drawn

		}



		// Drawing

		var dx = lineLayerBase - (cw>>1);

		var dy = lineLayerPos;



		drawTextToLayer(ll, dx, dy, text, chColor);



		// End drawing

		lastDrawnCh="";



		// Restore font

		lf.face = orgfont;

		lf.angle = organgle;



		// Hyperlink processing

		if(inLink!=-1)

		{

			// Hyperlinking

			ll.face = dfProvince;

			ll.fillRect(lineLayerBase - (fontSize>>1), lineLayerPos,

				fontSize, cw, numLinks+1);

			face = dfAuto;

			ll.face = dfAuto;

			linkFilled=true;

		}



		// Position update

		y += ch;

		lineLayerPos += ch;

		lineLayerLength += ch;



		lineLayer.visible = true;



		// Alignment correction

		if(align >= 0) adjustAlign();



		// Return

		return false;

	}



    var nameImageMap;

    var defaultNameImage;

    

    /**

     * Drawing the name

     */

    function processName(text="") {

		storeRedrawTextState("processName", text);

		//

        if (nameLayer !== void) {

            nameLayer.processName(text);

        }

    }



    function setNameImage(map, defaultImage) {

        nameImageMap = map;

        defaultNameImage = defaultImage;

    }

    

	function invalidateLinkObjects()

	{

		// Invalidate objects if assigned to link items

		for(var i = links.count-1; i>=0; i--)

		{

			if(links[i].type != ltNormal)

				invalidate links[i].object;

			links[i].type = 0;

		}

        (Dictionary.clear incontextof names)(); 

	}



	function beginLinkLine()

	{

		// Link start

		// Called when actual character drawing occurs after a link start tag

		// (Also called when moving to next line)

		if(linkFilled) return;

		var sx, sy;

		if(!vertical)

		{

			sx = lineLayerPos;

			sy = lineLayerBase - fontSize;

		}

		else

		{

			sx = lineLayerBase - (fontSize>>1);

			sy = lineLayerPos;

		}

		var n = links[numLinks].lineCount - 1;

		links[numLinks].fixed[n] = false; // Unfixed

		links[numLinks].x[n] = sx;

		links[numLinks].y[n] = sy;



		lineLayerLinks[lineLayerLinks.count] = %[number : numLinks, line : n];

		linkFilled = false;

	}



	function endLinkLine()

	{

		// Called when a line ends while in a link

		if(!linkFilled) return;

		linkFilled = false;

		var w, h;

		var linkn = links[numLinks];

		var linenum = links[numLinks].lineCount-1;

		if(!vertical)

		{

			w = lineLayerPos - linkn.x[linenum];

			if(lineLayer.font.italic) w += fontSize>>2; // Leave a little margin for italics

			if(w <= 0) return;

			h = fontSize;

		}

		else

		{

			w = fontSize;

			h = lineLayerPos - linkn.y[linenum];

			if(lineLayer.font.italic) h += fontSize>>2;

			if(h <= 0) return;

		}

		linkn.w[linenum] = w;

		linkn.h[linenum] = h;

		linkn.lineCount ++;

	}



	function createSoundExpression(exp, storage, buf)

	{

		// Create expression for playing sounds

		// Connect with comma if there was already an expression in exp

		// This specification might change later.

		if(storage == "") return exp;

		if(buf === void) buf = 0;

		var seexp = "(kag.se["+buf+"].play(%[storage:\"" + storage.escape() +"\"]))";

		if(exp != "")

			exp = seexp + ",("+exp+")";

		else

			exp = seexp;

		return exp;

	}



	function beginHyperLink(elm)

	{

		storeRedrawTextState("beginHyperLink", elm);

		// Start normal link

		links[numLinks] = %[ // Create dictionary array

			type :		ltNormal,

			storage :	elm.storage,

			target :	elm.target,

			exp :		createSoundExpression(elm.exp, elm.clickse, elm.clicksebuf),

			countPage :	(elm.countpage === void) ? true : +elm.countpage,

			hint :		elm.hint,

			color :		(elm.color === void) ? defaultLinkColor : +elm.color,

			opacity :	(elm.opacity === void) ? defaultLinkOpacity : +elm.opacity,

			onenter :	createSoundExpression(elm.onenter, elm.enterse, elm.entersebuf),

			onleave :	createSoundExpression(elm.onleave, elm.leavese, elm.leavesebuf),

			x :			[],

			y :			[],

			w :			[],

			h :			[],

			fixed :		[],

			lineCount :	1

			];

		inLink = 0;

	}



	function endHyperLink()

	{

		storeRedrawTextState("endHyperLink");

		//

		inLink = -1;

		endLinkLine();

		links[numLinks].lineCount--;

		numLinks++;

		focusable = true; // Capable of receiving focus

		lastMouseX = cursorX;

		lastMouseY = cursorY;

		selClickLock = true;

		setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

	}



	function findLink(x,y)

	{

		// Search for link at x, y position, return link number if found.



		if(selClickLock) return -1;



		var i=0;

		// Detection using area image

		if(lineLayer.visible)

		{

			if(lineLayer.left <= x && lineLayer.top <= y  &&

				lineLayer.imageWidth + lineLayer.left > x &&

				lineLayer.imageHeight + lineLayer.top > y)

			{

				i = lineLayer.getProvincePixel(x - lineLayer.left, y - lineLayer.top);

			}

		}

		if(i == 0) {

			// If textLayer exists, get from there

			var target = hasTextLayer ? textLayer : this;

			i = target.getProvincePixel(x, y);

		}

		if(i == -1) return -1;

		if(i != 0) return i - 1;

		return -1;

	}



    function getExistName(storage) {

        var test;

        if(!Storages.isExistentStorage(storage)) {

            if (test = storage + ".png", Storages.isExistentStorage(test))

                storage = test;

            else if (test = storage + ".tlg5", Storages.isExistentStorage(test))

                storage = test;

            else if (test = storage + ".tlg6", Storages.isExistentStorage(test))

                storage = test;

            else if (test = storage + ".bmp", Storages.isExistentStorage(test))

                storage = test;

            else

                storage = void;

        }

        return storage;

    }

    

	function addButton(elm)

	{

		// Place graphical button

        var object = new LinkButtonLayer(window, this);

        object.name =  elm.name !== void ? elm.name : "button" + numLinks;

        if (elm.uistates !== void) {

            object.loadUIInfo(elm);

			object.uiname = elm.uiname;

        } else if (elm.normal !== void) {

            var over   = elm.over !== void ? elm.over  : getExistName(elm.normal.replace(/_normal/, "_over"));

            var on     = elm.on   !== void ? elm.on    : getExistName(elm.normal.replace(/_normal/, "_on"));

            var focus  = elm.over !== void ? elm.focus : getExistName(elm.normal.replace(/_normal/, "_focus"));

            object.loadButtons(elm.normal, over, on, focus, elm.animcount, elm.animtime);

            if (elm.trigger || elm.group) {

                object.loadButtons(elm.on, over, on, focus, elm.animcount, elm.animtime, true);

                object.groupName = elm.group;

            }

        } else {

            if (elm.graphic == "") {

                var normal = elm.name + "_normal";

                var over   = elm.over !== void ? elm.over  : getExistName(elm.name + "_over");

                var on     = elm.on   !== void ? elm.on    : getExistName(elm.name + "_on");

                var focus  = elm.over !== void ? elm.focus : getExistName(elm.name + "_focus");

                object.loadButtons(normal, over, on, focus, elm.animcount, elm.animtime);

                if (elm.trigger || elm.group) {

                    object.loadButtons(elm.on, over, on, focus, elm.animcount, elm.animtime, true);

                    object.groupName = elm.group;

                }

            } else {

                object.loadImages(elm.graphic, elm.graphickey, elm.animcount, elm.animtime);

                if (elm.trigger || elm.group != "") {

					if (elm.graphicon != "") {

						object.loadImages(elm.graphicon, elm.graphickey, elm.animcount, elm.animtime, true);

					} else {

						//dm("makeToggle", elm.name);

						object.makeToggle();

					}

                    object.groupName = elm.group;

                }

            }

        }

        object.linkNum = numLinks;

        object.setPos(x, y);

		object.hint = elm.hint;

        object.visible = (elm.visible !== void) ? elm.visible : true;

		object.onenter = createSoundExpression(elm.onenter, elm.enterse, elm.entersebuf);

		object.onleave = createSoundExpression(elm.onleave, elm.leavese, elm.leavesebuf);

        object.hitThreshold = (elm.recthit === void || +elm.recthit) ? 0 : 64;

        if (elm.enabled !== void) {

            object.enabled = !!elm.enabled;

        } else if (elm.disabled !== void && elm.disabled) {

            object.enabled = false;

        }

        object.halftone = elm.halftone if elm.halftone !== void;



		links[numLinks] = %[

			type :			ltButton,

			graphic :		elm.graphic,

			graphickey :	elm.graphickey,

			storage :		elm.storage,

			target :		elm.target,

			exp :			createSoundExpression(elm.exp, elm.clickse, elm.clicksebuf),

			countPage :		(elm.countpage === void) ? true : +elm.countpage,

			object :		object,

			onenter :		object.onenter,

			onleave :		object.onleave,

			x :				[x],

			y :				[y],

			w :				[object.width],

			h :				[object.height],

			fixed :			[true],

			lineCount :		1

			];

        names[object.name] = object;



		numLinks++;

		focusable = true; // Capable of receiving focus

		setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

	}



	function addEdit(elm)

	{

		// Place single-line edit

		changeLineSize() if sizeChanged;



		var object = new LinkEditLayer(window, this, vertical);

		object.name = elm.name !== void ? elm.name : "edit" + numLinks;

		var of = object.font;

		var lf = lineLayer.font;

		of.face   = (elm.fontface   !== void) ? elm.fontface   : lf.face;

		of.angle  = (elm.fontangle  !== void) ? elm.fontangle  : lf.angle;

		of.bold   = (elm.fontbold   !== void) ? elm.fontbold   : lf.bold;

		of.italic = (elm.fontitalic !== void) ? elm.fontitalic : lf.italic;

		of.height = (elm.fontheight !== void) ? elm.fontheight : lf.height;



		object.linkNum = numLinks;

		var exp = (elm.exp != "") ? elm.exp : elm.name;

		object.text = Scripts.eval(exp);

		object.exp  = exp;

		object.antialiased = antialiased;

		object.color = elm.bgcolor if elm.bgcolor !== void; // Note: NOT color

		object.textColor = elm.color if elm.color !== void; // Note: NOT textColor

		object.maxChars = elm.maxchars if elm.maxchars !== void;

		object.bgOpacity = elm.opacity if elm.opacity !== void;

		object.noborder = elm.noborder if elm.noborder !== void;



		var ox = 0, oy = 0;

		ox = +elm.textox if (elm.textox !== void);

		oy = +elm.textoy if (elm.textoy !== void);

		object.setDrawTextOffset(ox, oy) if (ox != 0 || oy != 0);



		var len = elm.length === void ? 200: +elm.length;

		var fh = Math.abs(of.height);

		if (elm.nofixpos) {

			// Option to not correct position added

			object.setPos(x, y);

			if(vertical) {

				object.height = len;

				object.width = fh + 6;

			} else {

				object.width  = len;

				object.height = fh + 6;

			}

		} else {

			if(vertical)

			{

				object.setPos(lineLayer.left + lineLayerBase - ((lf.height + 6)>>1),

							  lineLayer.top + lineLayerPos);

				object.height = len;

				object.width = lf.height + 6;

				y += len;

			}

			else

			{

				object.setPos(lineLayer.left + lineLayerPos,

							  lineLayer.top + lineLayerBase - fontSize - 3);

				object.width = elm.length === void ? 200: +elm.length;

				object.height = lf.height + 6;

				x += len;

			}

		}

		object.visible = (elm.visible !== void) ? elm.visible : true;



        lineLayerPos += len;

		lineLayerLength += len;



		links[numLinks] = %[

			type :			ltEdit,

			exp :			exp,

			object :		object,

			x :				[object.left],

			y :				[object.top],

			w :				[object.width],

			h :				[object.height],

			fixed :			[true],

			lineCount :		1

			];

        names[object.name] = object;



		numLinks ++;

		focusable = true;

		setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

	}



	function addCheckBox(elm)

	{

		var object = new LinkCheckBoxLayer(window, this, vertical);

        object.name = elm.name !== void ? elm.name : "check" + numLinks;

        object.linkNum = numLinks;

		object.vertical = vertical;

		object.checked = Scripts.eval(elm.name);

		object.exp = elm.name;

        object.changefuncdata = Scripts.eval(elm.onchangefuncdata) if elm.onchangefuncdata !== void;

        object.changefunc = elm.onchangefunc if elm.onchangefunc !== void;

        object.change = elm.onchange if elm.onchange !== void;

        object.changese = createSoundExpression(void, elm.changese, elm.changesebuf);

        object.color = elm.bgcolor if elm.bgcolor !== void; // Note: NOT color

		object.glyphColor = elm.color if elm.color !== void; // Note: NOT glyphColor

		object.bgOpacity = elm.opacity if elm.opacity !== void;



		var cw;

		var lw = object.width;

		var lh = object.height;

		if(vertical)

		{

			if(lw > lineSize) lineSize = lw; else lw = object.width = lineSize; // Expand

			cw = lh;

		}

		else

		{

			if(lh > lineSize) lineSize = lh; else lh = object.height = lineSize; // Expand

			cw = lw;

		}



		changeLineSize();



		var cx,cy;

		if(vertical)

		{

			cx = lineLayerBase - (lw>>1);

			cy = lineLayerPos;

		}

		else

		{

			cx = lineLayerPos;

			cy = lineLayerBase - lh;

		}



		object.setPos(cx + lineLayerOriginX + getLineLayerLeftOffset(),

					cy + lineLayerOriginY + getLineLayerTopOffset());



		if(vertical) y+=cw; else x+=cw;

		lineLayerPos += cw;

		lineLayerLength += cw;



		object.visible = (elm.visible !== void) ? elm.visible : true;



		links[numLinks] = %[

			type :			ltCheckBox,

			exp :			elm.name,

			object :		object,

			x :				[object.left],

			y :				[object.top],

			w :				[object.width],

			h :				[object.height],

			fixed :			[true], // Fixed!!!

			lineCount :		1

			];

        names[object.name] = object;



		numLinks ++;

		focusable = true;

		setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

	}



	function addSlider(elm)

	{

		var vert = elm.vertical !== void ? +elm.vertical : vertical;

        var object = new LinkSliderLayer(window, this, vert);

        object.name = elm.name !== void ? elm.name : "slider" + numLinks;

        object.linkNum = numLinks;

		object.onclick = createSoundExpression(elm.exp, elm.clickse, elm.clicksebuf);

		object.onenter = createSoundExpression(elm.onenter, elm.enterse, elm.entersebuf);

		object.onleave = createSoundExpression(elm.onleave, elm.leavese, elm.leavesebuf);

		object.exp     = elm.exp;

        object.color = elm.bgcolor if elm.bgcolor !== void; // Note: NOT color

        object.bgOpacity = elm.opacity if elm.opacity !== void;

		object.min  = +elm.min  if elm.min  !== void;

		object.max  = +elm.max  if elm.max  !== void;

		object.step = +elm.step if elm.step !== void;

        object.nohilight = elm.nohilight if elm.nohilight !== void;

        object.jumpMode = elm.jumpmode if elm.jumpmode !== void;

        if (elm.value !== void) {

            object.position = +Scripts.eval(elm.value);

            object.change = elm.value;

        } else {

            object.position = +elm.position if elm.position !== void;

            object.changefuncdata = Scripts.eval(elm.onchangefuncdata) if elm.onchangefuncdata !== void;

            object.changefunc = elm.onchangefunc if elm.onchangefunc !== void;

            object.change = elm.onchange if elm.onchange !== void;

        }

        object.changese = createSoundExpression(void, elm.changese, elm.changesebuf);



        if (elm.uistates !== void) {

            object.loadUIInfo(elm); 

			object.uiname = elm.uiname;

       } else {

            // Base specification

            if (elm.base !== void) {

                object.loadBase(elm.base);

            } else {

                object.width   = elm.width  === void ? 200 : +elm.width;

                object.height  = elm.height === void ? 30  : +elm.height;

            }

            // Tab specification

            if (elm.normal !== void) {

                object.loadTabs(elm.normal, elm.over, elm.on);

            } else if (elm.tab !== void) {

                object.loadTab(elm.tab);

            }

        }



		// Option to not correct position added

		if (elm.nofixpos) {

			object.setPos(x, y);

		} else {

			var cw;

			var lw = object.width;

			var lh = object.height;

			if(vertical) {

				if (lw > lineSize) lineSize = lw;

				else lw = object.width = lineSize; // Expand

				cw = lh;

			} else {

				if (lh > lineSize) lineSize = lh;

				else lh = object.height = lineSize; // Expand

				cw = lw;

			}

			changeLineSize();



			var cx,cy;

			if(vertical) {

				cx = lineLayerBase - (lw>>1);

				cy = lineLayerPos;

			} else {

				cx = lineLayerPos;

				cy = lineLayerBase - lh;

			}



			cx += +elm.ox if elm.ox !== void;

			cy += +elm.oy if elm.oy !== void;



			object.setPos(cx + lineLayerOriginX + getLineLayerLeftOffset(),

						  cy + lineLayerOriginY + getLineLayerTopOffset());



			if(vertical) y+=cw; else x+=cw;

			lineLayerPos += cw;

			lineLayerLength += cw;

		}



        object.visible = (elm.visible !== void) ? elm.visible : true;



        links[numLinks] = %[

			type :			ltSlider,

			exp :			elm.exp,

			object :		object,

			onenter :		object.onenter,

			onleave :		object.onleave,

			x :				[object.left],

			y :				[object.top],

			w :				[object.width],

			h :				[object.height],

			fixed :			[true], // Fixed!!!

			lineCount :		1

			];

        names[object.name] = object;



        numLinks ++;

        focusable = true;

        setSelProcessLock(false); // Release selection lock

        //comp.setSelProcessLock(false); // Release selection lock

	}



    /**

     * Registration of system buttons

     */

    function addSystemButton(elm) {

        var object = new SystemButtonLayer(window, this);

        object.name =  elm.name != "" ? elm.name : ("sysbutton" + buttons_save.count);

        if (elm.uistates !== void) {

            object.loadUIInfo(elm);

			object.uiname = elm.uiname;

        } else if (elm.normal !== void) {

            var over   = elm.over !== void ? elm.over  : getExistName(elm.normal.replace(/_normal/, "_over"));

            var on     = elm.on   !== void ? elm.on    : getExistName(elm.normal.replace(/_normal/, "_on"));

            var focus  = elm.over !== void ? elm.focus : getExistName(elm.normal.replace(/_normal/, "_focus"));

            object.loadButtons(elm.normal, over, on, focus, elm.animcount, elm.animtime);

        } else {

            if (elm.graphic == "") {

                var normal = elm.name + "_normal";

                var over   = elm.over !== void ? elm.over  : getExistName(elm.name + "_over");

                var on     = elm.on   !== void ? elm.on    : getExistName(elm.name + "_on");

                var focus  = elm.over !== void ? elm.focus : getExistName(elm.name + "_focus");

                object.loadButtons(normal, over, on, focus, elm.animcount, elm.animtime);

            } else {

                object.loadImages(elm.graphic, elm.graphickey, elm.animcount, elm.animtime);

                if (elm.graphicon != "") {

                    object.loadImages(elm.graphicon, elm.graphickey, elm.animcount, elm.animtime, true);

                }

            }

        }

        object.setPos(elm.x, elm.y);

        object.hint = elm.hint;

        object.visible = (elm.visible !== void) ? elm.visible : true;

        object.onclick = createSoundExpression(elm.exp, elm.clickse, elm.clicksebuf);

		object.onenter = createSoundExpression(elm.onenter, elm.enterse, elm.entersebuf);

        object.onleave = createSoundExpression(elm.onleave, elm.leavese, elm.leavesebuf);

		var islay = elm.class == "layer", en = true;

        object.hitThreshold = (islay || elm.recthit === void || +elm.recthit) ? 0 : 64;

		object.hitType      = (islay || !!+elm.nohit) ? htProvince : htMask;

		object.absolute     = +elm.absolute if (elm.absolute !== void);

		en = !!elm.enabled if (elm.enabled  !== void);

		en = false         if (islay || (elm.disabled !== void && elm.disabled));

		object.enabled = en;

        object.noStable = elm.nostable;

        object.halftone = elm.halftone if elm.halftone !== void;

        buttons[object.name] = object;



        // Save information

        var init = %[];

        (Dictionary.assign incontextof init)(elm, false); 

        buttons_save.add(init);

    }

    

	function highlightLink(n, b = false)

	{

		// Highlights the n-th link

		// b : true  : Highlight

		// b : false : Remove highlight

		if(selProcessLock) return;

		if(b)

		{

			if(n < 0 || n >= numLinks) return;

			var linkn = links[n];

			if(linkn === void) return;

			if(linkn.type != ltNormal) return;

			var xofs = lineLayerOriginX + getLineLayerLeftOffset();

			var yofs = lineLayerOriginY + getLineLayerTopOffset();



            if(linkn.onenter != '') Scripts.eval(linkn.onenter);



			// Highlight

			if(!vertical)

			{

				// Horizontal

				// Obtain min/max positions to avoid full screen updates

				var min = linkn.y[0];

				if(!linkn.fixed[0]) min += yofs; // Correct if not fixed

				var max = linkn.y[0] + linkn.h[0];

				if(!linkn.fixed[0]) max += yofs;



				var i;

				for(i = 0; i < linkn.lineCount; i++)

				{

					var m;

					m = linkn.y[i];

					if(!linkn.fixed[i]) m += yofs;

					if(min > m) min = m;

					m = linkn.y[i] + linkn.h[i];

					if(!linkn.fixed[i]) m += yofs;

					if(max < m) max = m;

				}



				highlightLayer.setPos(0, min);

				highlightLayer.setImageSize(imageWidth, max - min);

				highlightLayer.setSizeToImageSize();

			}

			else

			{

				// Vertical

				var min = linkn.x[0];

				if(!linkn.fixed[0]) min += xofs;

				var max = linkn.x[0] + linkn.w[0];

				if(!linkn.fixed[0]) max += xofs;



				var i;

				for(i = 0; i < linkn.lineCount; i++)

				{

					var m;

					m = linkn.x[i];

					if(!linkn.fixed[i]) m += xofs;

					if(min > m) min = m;

					m = linkn.x[i] + linkn.w[i];

					if(!linkn.fixed[i]) m += xofs;

					if(max < m) max = m;

				}



				highlightLayer.setPos(min, 0);

				highlightLayer.setImageSize(max - min, imageHeight);

				highlightLayer.setSizeToImageSize();

			}



			with (highlightLayer) {

				.fillRect(0, 0, .imageWidth, .imageHeight, 0);

				.face = dfProvince;

				.fillRect(0, 0, .imageWidth, .imageHeight, 0);

				.face = dfAuto;

			}



			var i;

			for(i = 0; i < linkn.lineCount; i++)

			{

				var x = linkn.x[i];

				var y = linkn.y[i];

				if(!linkn.fixed[i]) x += xofs, y += yofs;



				drawHighlight(highlightLayer, linkn, i, x, y, linkn.w[i], linkn.h[i], linkn.color, linkn.opacity);

			}



			highlightLayer.visible = true;



			cursor = window.cursorPointed;



			if(parent.isPrimary && comp !== void && left == comp.left && top == comp.top &&

				width == comp.width && height == comp.height)

			{

				// Set background page layer similarly

				var tl = highlightLayer;

				var bl = comp.highlightLayer;

				bl.assignImages(tl);

				bl.setPos(tl.left, tl.top, tl.width, tl.height);

				bl.visible = true;

			}



			// Set hint

			hint = links[n].hint;

		}

		else

		{

			if(n >= 0 && n < numLinks)

			{

				if(links[n] !== void && links[n].type == ltNormal)

				{

					if(links[n].onleave != '') Scripts.eval(links[n].onleave);

				}

			}



			highlightLayer.visible = false;

			cursor = crDefault;



			if(/*parent.isPrimary && */comp !== void)

				comp.highlightLayer.visible = false;



			showParentHint = false;

		}

	}

	function drawHighlight(layer, linkn, i, x, y, w, h, color, opacity) {

		// Highlight fill process

		with (layer) .colorRect(x - .left, y - .top, w, h, color, opacity);

	}



    function updateRadio(button) {

        for(var i = links.count-1; i>=0; i--) {

            var l = links[i];

            if (l.type == ltButton && l.object !== button && l.object.groupName == button.groupName) {

                l.object.toggle = false;

            }

        }

    }

    

	function processLink(n)

	{

        // Stop timeout process

        stopTimeout();



        // Process link number n

		var ln = links[n];

		if(ln === void) return;



        // XXX Tried adding this

		if (ln.object !== void) with (ln.object) {

			if (!(typeof .canExecute == "Object" ? .canExecute() : .enabled)) return;

		}



        // Special handling for buttons

        if (ln.type == ltButton) {

            var button = ln.object;

            if (button.groupName != "") {

                button.toggle = true;

            } else if (button.toggleButton) {

                button.toggle = !button.toggle;

            }

        }



        // Hide highlight on background screen

		if(comp !== void) comp.highlightLayer.visible = false;



		// Execution

		Scripts.eval(ln.exp) if ln.exp != '';



		if(ln.storage != '' || ln.target != '')

		{

			window.lockMessageLayerSelProcess(); // Lock selection

			if(window.getKeyState(VK_RETURN) || window.getKeyState(VK_SPACE) || window.getKeyState(VK_CONTROL))

				window.hideMouseCursor();

					// Hide mouse cursor if operated by keyboard

			window.process(ln.storage, ln.target, ln.countPage);

		}

    }



	function onButtonClick(num)

	{

        // Graphical button with number num clicked

		processLink(num);

    }





	function setSelProcessLock(b)

	{

		// Set selection lock

		// Locking selection is to prevent other options from being selected

		// once an option has been selected.

		if(selProcessLock != b)

		{

			selProcessLock = b;

			var lks = links;

			for(var i = 0; i < numLinks; i++)

			{

				var item = lks[i];

				var type = item.type;

				if(type == ltButton) item.object.eventTransparent = b;

                else if(type == ltEdit || type == ltCheckBox || type == ltSlider) item.object.enabled = !b;

            }

        }

        if (selProcessLock) {

            focusable = false;

        } else {

            if (numLinks > 0 || hasWheel() || hasClick()) {

                focusable = true;

            }

        }

    }



	function storeSelProcessLock()

	{

		// Called before entering right-click subroutine to save the current selProcessLock state.

		storedSelProcessLock = selProcessLock;

	}



	function restoreSelProcessLock()

	{

		// Called when exiting right-click routine to restore the state of selProcessLock before the routine.

		setSelProcessLock(storedSelProcessLock);

	}



	function commit()

	{

		// Commit form elements' content

		var lks = links;

		for(var i = 0; i < numLinks; i++)

		{

			var item = lks[i];

			var type = item.type;

            if(type == ltEdit || type == ltCheckBox || type == ltSlider) item.object.commit();

		}

	}



	function isDragPos(x, y)

	{

		// Whether coordinates x, y are positions that can be grabbed for dragging

		if(!draggable) return false;

		if(x >= marginL && y >= marginT && x < imageWidth - marginR && y < imageHeight - marginB)

			return false;

		if(x<0 || y<0 || x>=imageWidth || y>=imageHeight) return false;

		return getMaskPixel(x, y) >= 64;

	}



	function internalHitTest(x, y)

	{

        // onHitTest event handler (internal function)



		if(isDragPos(x, y))

		{

			cursor = window.cursorDraggable;

			showParentHint = true;

			return true; // Opaque

		}



		if(selClickLock)

		{

			// Check if mouse has moved a certain distance from where it was last clicked.

			// This is to prevent accidental selection due to repeated clicks.

			if(lastMouseX-3 > x || lastMouseX+3 < x ||

				lastMouseY-3 > y || lastMouseY+3 < y)

			{

				selClickLock = false;

			}

		}



        if (!eventTransparent) return true;



		if (selProcessLock) return false; // Transparent

        

		var n;

		n = findLink(x, y);

        if(n == -1)

		{

            return hasClick(); // Transparent if no click process

		}

		else

		{

			cursor = window.cursorPointed;

			return true; // Not transparent

		}

	}



	function onHitTest(x, y, b)

	{

		// onHitTest event handler

		var b = internalHitTest(x - imageLeft, y - imageTop);

		return super.onHitTest(x, y, b);

	}



	function internalOnMouseDown(x, y, button)

	{

        // onMouseDown event handler (internal function)

		if(button == mbLeft && !selProcessLock)

		{

            if(!selClickLock)

			{

                var n = findLink(x, y);



				if(n != -1)

				{

					processLink(n);

					return;

                } else if (hasClick()) {

                    processClick();

                    return;

                }

			}

		}



		if(isDragPos(x, y))

		{

			// In draggable position

			if(window.inStable)

			{

				dragOriginX = x;

				dragOriginY = y;

				dragging = true; // Drag start

			}

		}

	}



	function onMouseDown(x, y, button)

	{

        lastMouseDownX = x;

		lastMouseDownY = y;



        // Pass right clicks through

        if (button == mbRight) {

			releaseCapture();

            window.onPrimaryRightClick();

        }

        

		internalOnMouseDown(x - imageLeft, y - imageTop, button);



		super.onMouseDown(...);

	}



	function onMouseUp(x, y, button)

	{

		dragging = false;



		super.onMouseUp(...);

	}



	function cancelDrag()

	{

		// Cancel dragging

		dragging = false;

	}



	function internalMouseMove(x, y)

	{

		// Called from onMouseMove, etc.

		if(dragging)

		{

			// Dragging

			var px = parent.cursorX;

			var py = parent.cursorY;

			if(px < 0) px = 0;

			if(py < 0) py = 0;

			if(px >= parent.width) px = parent.width -1;

			if(py >= parent.height) py = parent.height -1;

			var l = px - dragOriginX;

			var t = py - dragOriginY;

			setPos(l, t);

			return;

		}





		if(selProcessLock)

		{

			// Do nothing during selection lock

			if(cursor == window.cursorPointed) cursor = crDefault; // Just because...

			return;

		}



		var n = findLink(x, y); // Check if there is a link at x, y position



		if(n != lastLink)

		{

			if(lastLink != -1)

			{

				highlightLink(lastLink, false);

			}

			if(n != -1)

			{

				highlightLink(n, true);

			}

			lastLink = n;

			keyLink = lastLink;

		}

	}

	



    function onMouseMove(x, y)

	{

        // onMouseMove event handler

        super.onMouseMove(...);



		internalMouseMove(x - imageLeft, y - imageTop);

	}



    function onMouseLeave()

	{

        // onMouseLeave event handler

		if(lastLink != -1)

		{

			highlightLink(lastLink, false);

			lastLink = -1;

		}

		super.onMouseLeave(...);

	}



	function getLinkHotSpot(linkn)

	{

		var left   = linkn.x[0];

		var top    = linkn.y[0];

		var width  = linkn.w[0];

		var height = linkn.h[0];

		var x, y;

		if(linkn.type == ltEdit)

		{

			// Place cursor at edge so it doesn't get in the way

			if(vertical)

			{

				x = left + (width>>1);

				y = top;

			}

			else

			{

				x = left;

				y = top + (height>>1);

			}

		}

		else

		{

			x = left + (width>>1);

			y = top + (height>>1);

		}

		if(!linkn.fixed[0])

		{

			// unfixed

			x += lineLayerOriginX + getLineLayerLeftOffset();

			y += lineLayerOriginY + getLineLayerTopOffset();

		}

		return %[ x:x, y:y ];

	}



	function setFocusToLink(n, force = false)

	{

		// Move mouse cursor to link number n or give focus.

		// If force=false, cursor only moves if keyboard operation occurs; 

		// if force=true, cursor moves and focus is set regardless of keyboard state.

		var linkn = links[n];

		if(linkn === void) return;

		var x, y;

		with (getLinkHotSpot(linkn)) x=.x, y=.y;



		// Check if the corresponding key is pressed, 

		// so cursor only moves if keyboard operation occurred.

		var sgks = window.getKeyState;

		var process = force || sgks(VK_LEFT) || sgks(VK_UP) || sgks(VK_RIGHT) ||

			sgks(VK_DOWN) || sgks(VK_TAB) || sgks(VK_RETURN);

		if(process)

		{

			selClickLock = false;

			cursorX = x;

			cursorY = y;

			internalMouseMove(x, y);

			if(force) keyLink = n; // Tentative reset

		}

		if(linkn.type == ltEdit || linkn.type == ltCheckBox || linkn.type == ltSlider)

		{

			var obj = linkn.object;

			if(force) obj.focus();

			return obj;

		}

		if(force) focus();

		return void;

	}



    function checkFocus(link, direction) {

        var firstLink = link;

        do {

            var target = links[link].object;

            if (target === void || !isvalid target || (target.visible && target.enabled)) {

                return link;

            }

            if (direction > 0) {

                link++;

                if (link >= numLinks) {

                    link = 0;

                }

            } else {

                link--;

                if (link < 0) {

                    link = numLinks - 1;

                }

            }

        } while (link != firstLink);

        return -1;

    }



    function tabPrev(force = false) {

		selClickLock = false;

		keyLink = lastKeyLink if (keyLink < 0 && lastKeyLink >= 0);

		if(keyLink == -1 || keyLink == 0)

		{

//			var l = focusPrev();

//			if(l !== null) return;

			keyLink = numLinks - 1;

		}

		else

		{

			keyLink--;

		}

		keyLink = checkFocus(keyLink, -1);

		if (keyLink < 0) return;

		var obj = setFocusToLink(keyLink, force);

		if(obj !== void) obj.focus();

    }

    

    function tabNext(force = false) {

		selClickLock = false;

		keyLink = lastKeyLink if (keyLink < 0 && lastKeyLink >= 0);

		if(keyLink == -1 || keyLink == numLinks -1)

		{

//			var l = focusNext();

//			if(l !== null) return;

			keyLink = 0;

		}

		else

		{

			keyLink ++;

		}

		keyLink = checkFocus(keyLink, 1);

		if (keyLink < 0) return;

		var obj = setFocusToLink(keyLink, force);

		if(obj !== void) obj.focus();

    }

    

	function onKeyDown(key, shift)

	{

		// Key pressed

		if(window.preProcessKeys(key, shift)) return;



		if(!focusable || (!numLinks && !hasClick())) { return super.onKeyDown(...); }



		var l, r;

		if(vertical)

		{

			l=VK_RIGHT;

			r=VK_LEFT;

		}

		else

		{

			l=VK_LEFT;

			r=VK_RIGHT;

		}



		if(!selProcessLock && ((key == VK_UP && !(shift & ssShift)) || key == l || (key == VK_TAB && (shift & ssShift))))

		{

			releaseCapture();

            tabPrev();

        }

		else if(!selProcessLock && (key == VK_DOWN || key == r || (key == VK_TAB && !(shift & ssShift))))

		{

			releaseCapture();

            tabNext();

		}

		else if(key == VK_SPACE || key == VK_RETURN)

		{

            selClickLock = false;

            if(selProcessLock || keyLink == -1) {

                if (hasClick()) {

                    processClick();

                } else {

                    window.checkProceedingKey(key, shift);

                }

            } else {

                if (keyLink != -1 && links[keyLink].type == ltEdit) {

                    tabNext();

                } else {

                    processLink(keyLink);

                }

            }

		}

		else

		{

			window.processKeys(key, shift); // Leave processing to window

		}

	}



	function findPrevFocusable(control, layer)

	{

        if(control.linkNum != 0) return this; else return prevFocusable;

	}



	function findNextFocusable(control, layer)

	{

		if(control.linkNum != numLinks -1) return this; else return layer;

	}



	function onBeforeFocus(layer, blured, direction)

	{

        // Called before getting focus

		// Move cursor to first link



		if(!selProcessLock)

		{

			// Check if corresponding key is pressed so cursor only moves if keyboard operation occurred.

			var sgks = window.getKeyState;

			var process = sgks(VK_LEFT) || sgks(VK_UP) || sgks(VK_RIGHT) ||

				sgks(VK_DOWN) || sgks(VK_TAB);



			if(process && (blured == null || blured.parent != this))

			{

				if(direction)

				{

					// forward

					keyLink = 0;

				}

				else

				{

					// backward

					keyLink = numLinks-1;

				}

                keyLink = checkFocus(keyLink, direction ? 1 : -1);

				var obj = setFocusToLink(keyLink);

				if(obj !== void)

				{

					super.onBeforeFocus(obj, blured, direction);

					return;

				}

			}



			if(blured != null && blured.parent == this)

			{

				if(direction)

				{

					if(keyLink == -1 || keyLink == numLinks -1)

						keyLink = 0;

					else

						keyLink++;

				}

				else

				{

					if(keyLink == -1 || keyLink == 0)

						keyLink = numLinks - 1;

					else

						keyLink--;

				}

				//dm("keyLink:" + keyLink);

				//dm("numLinks:" + numLinks);

                keyLink = checkFocus(keyLink, direction ? 1 : -1);

				var obj = setFocusToLink(keyLink);

				if(obj !== void)

				{

					super.onBeforeFocus(obj, blured, direction);

					return;

				}

			}

		}



		super.onBeforeFocus(...);

	}



	function locate(newx, newy)

	{

		storeRedrawTextState("locate", newx, newy);

		//

		var dx = +newx + marginL - x;

		var dy = +newy + marginT - y;



		if(newx !== void)

			x = +newx + marginL;



		if(newy !== void)

			y = +newy + marginT;



		if(!vertical && newy === void)

		{

			// Horizontal position change only

			lineLayerPos += dx;

			lineLayerLength += dx;

		}

		else if(vertical && newx === void)

		{

			// Vertical position change only

			lineLayerPos += dy;

			lineLayerLength += dy;

		}

		else

		{

			if(newx === void || newy === void)

			{

				if(vertical) y = marginT; else x = marginL;

			}

			if(inLink!=-1) endLinkLine();

			fixLineLayer();

			decideSizeChange();

			initLineLayer();

		}

	}



	function processReturn()

	{

		storeRedrawTextState("processReturn");

		// Process line break

		if(reline())

		{

			return autoReturn;

		}

		return false;

	}



	function processGraph(elm)

	{

		stopChFade();

		storeRedrawTextState("processGraph", elm);

		// Display inline image according to elm

		var key = adjustColorKey(elm.key);

		var char = true;

		char = +elm.char if elm.char !== void;

		var r = putGraph(elm.storage, key, char);

		return r ? autoReturn : r;

	}



	function setRuby(text)

	{

		storeRedrawTextState("setRuby", text);

		// Set ruby for the next character

		currentRuby = text;

	}



	function showBreakGlyph(glyphobj, storage, key, baseLine=0)

	{

		// Display line break/page break glyphs on screen

		glyphobj.parent = this; // Make itself the parent

		glyphobj.loadImages(storage, key); // Load images

		glyphobj.bringToFront(); // To front



		if(glyphFixedSize)

		{

			glyphobj.setSize(glyphFixedWidth, glyphFixedHeight);

		}



        if(glyphFixedPosition)

		{

			glyphobj.setPos(glyphFixedLeft, glyphFixedTop + baseLine);

		}

		else

		{

			if(!vertical)

			{

				glyphobj.setPos(lineLayerPos + lineLayerOriginX + getLineLayerLeftOffset(),

					y + lineSize + lineSpacing - glyphobj.height + baseLine);

			}

			else

			{

				glyphobj.setPos(x - lineSpacing-  (lineSize>>1) - (glyphobj.width>>1) + baseLine,

					lineLayerPos + lineLayerOriginY + getLineLayerTopOffset());

			}

		}

        glyphobj.visible = true;

	}



	function showLineBreakGlyph(glyphobj)

	{

        // Show line break glyph

        showBreakGlyph(glyphobj, lineBreakGlyph, lineBreakGlyphKey, lineBreakBaseLine);

	}



	function showPageBreakGlyph(glyphobj)

	{

		// Show page break glyph

		showBreakGlyph(glyphobj, pageBreakGlyph, pageBreakGlyphKey, pageBreakBaseLine);

	}



	function setGlyph(elm)

	{

		// Set click-wait glyphs

		if(elm.line !== void)

		{

			lineBreakGlyph = elm.line;

			lineBreakGlyphKey = elm.linekey;

		}

		if(elm.page !== void)

		{

			pageBreakGlyph = elm.page;

			pageBreakGlyphKey = elm.pagekey;

		}

		glyphFixedPosition = +elm.fix if elm.fix !== void;

		glyphFixedLeft = +elm.left if elm.left !== void;

		glyphFixedTop = +elm.top if elm.top !== void;

	}



	function preIndent(ch)

	{

		changeLineSize() if sizeChanged;

		var cw = (typeof ch == "String") ? lineLayer.font.getTextWidth(ch) : +ch;

		var newx = x - marginL, newy = y - marginT;

		if(vertical) newy -= cw;

		else         newx -= cw;

		locate(newx, newy);

	}

	function setIndent()

	{

		storeRedrawTextState("setIndent");

		// Set indent to current position

		if(vertical) indentxpos = y - marginT; else indentxpos = x - marginL;

	}



	function resetIndent()

	{

		storeRedrawTextState("resetIndent");

		// Remove indent

		indentxpos = 0;

	}



	function assignComp()

	{

		// Copy content of paired layer

        assign(comp);

	}



	function beginTransition(elm)

	{

		// Perform transition according to elm

		faceLayer.stopTransition() if faceLayer !== void;

		super.beginTransition(elm, comp);

	}

	function stopTransition()

	{

		faceLayer.stopTransition() if faceLayer !== void;

		return super.stopTransition(...);

	}



	function internalAssign(src, copyvisiblestate)

	{

        // Copy layer information

		// (Execution takes time as there's massive amount of info to copy)



		// Copy layer's image, position, transparency etc.

		assignImages(src);

		if(copyvisiblestate)

			assignVisibleState(src); // assignImages doesn't copy visibility info etc.



		focusable = src.focusable;



        eventTransparent = src.eventTransparent;

        

		// Copy links

		{

			invalidateLinkObjects(); // Invalidate all objects just in case

			var tl = links, sl = src.links;

			tl.count = sl.count;

			for(var i = sl.count-1; i>=0; i--)

			{

				if(sl[i] === void) continue;

				var tl_d = (tl[i] = %[]);

				var sl_d = sl[i];

				(Dictionary.assign incontextof tl_d)(sl_d);

				// Must manually assign x, y, w, h, fixed members

				(tl_d.x = []).assign(sl_d.x);

				(tl_d.y = []).assign(sl_d.y);

				(tl_d.w = []).assign(sl_d.w);

				(tl_d.h = []).assign(sl_d.h);

				(tl_d.fixed = []).assign(sl_d.fixed);



				// Depending on type

				var type = tl_d.type;

				if(type == ltButton || type == ltLayer)

				{

					// Button

					var sl_d_object = sl_d.object;

					var object = new LinkButtonLayer(window, this);

						// Re-create object

					object.assign(sl_d_object);

					tl_d.object = object;

                    names[object.name] = object;

					if (type == ltLayer) with (object) .enabled = .focusable = false;

				}

				else if(type == ltEdit)

				{

					// Single-line edit

					var sl_d_object = sl_d.object;

					var object = new LinkEditLayer(window, this);

						// Re-create object

					object.assign(sl_d_object);

					tl_d.object = object;

                    names[object.name] = object;

				}

				else if(type == ltCheckBox)

				{

					// Checkbox

					var sl_d_object = sl_d.object;

					var object = new LinkCheckBoxLayer(window, this);

						// Re-create object

					object.assign(sl_d_object);

					tl_d.object = object;

                    names[object.name] = object;

                }else if(type == ltSlider)

				{

					// Slider

					var sl_d_object = sl_d.object;

					var object = new LinkSliderLayer(window, this);

						// Re-create object

					object.assign(sl_d_object);

					tl_d.object = object;

                    names[object.name] = object;

                }

			}

		}





		// Copy lineLayerLinks

		{

			var tl = lineLayerLinks, sl = src.lineLayerLinks;

			tl.count = sl.count;

			for(var i = sl.count-1; i>=0; i--)

			{

				(Dictionary.assign incontextof (tl[i] = %[]))(sl[i]);

			}

		}



		// Copy lineLayer position, size, image, font info

		{

			var tl = lineLayer, sl = src.lineLayer;

			tl.assignImages(sl);

			tl.assignVisibleState(sl);

			var tf = tl.font, sf = sl.font;

			tf.face = sf.face;

			tf.angle = sf.angle;

			tf.bold = sf.bold;

			tf.italic = sf.italic;

			tf.height = sf.height;

		}



		// Copy textLayer if exists

		if (src.hasTextLayer) {

			hasTextLayer = true if (!hasTextLayer);

			var st = src.textLayer;

			with (textLayer) {

				.assignImages(st);

				.assignVisibleState(st);

			}

		}



		// Miscellaneous

		highlightLayer.visible = false;

		keyLink = -1;

		imageModified = true;



		// Copy other information

		// The parts between [start_assign_vars] and [end_assign_vars]

		// are auto-generated by perl; do not edit or delete these marks.

		// [start_assign_vars]

		frameGraphic = src.frameGraphic;

		frameKey = src.frameKey;

        frameAnimCount = src.frameAnimCount;

        frameAnimTime  = src.frameAnimTime;

        frameColor = src.frameColor;

		frameOpacity = src.frameOpacity;

		marginL = src.marginL;

		marginT = src.marginT;

		marginR = src.marginR;

		marginB = src.marginB;

		marginRCh = src.marginRCh;

		x = src.x;

		y = src.y;

		relinexpos = src.relinexpos;

		isLastLine = src.isLastLine;

		indentxpos = src.indentxpos;

		linkFilled = src.linkFilled;

		numLinks = src.numLinks;

		selProcessLock = src.selProcessLock;

		storedSelProcessLock = src.storedSelProcessLock;

		defaultLinkColor = src.defaultLinkColor;

		defaultLinkOpacity = src.defaultLinkOpacity;

		defaultFontSize = src.defaultFontSize;

		nameLayerFontSize = src.nameLayerFontSize;

		fontSize = src.fontSize;

		_fontSize = src._fontSize;

		defaultLineSize = src.defaultLineSize;

		reserveLineSize = src.reserveLineSize;

		lineSize = src.lineSize;

		defaultRubySize = src.defaultRubySize;

		rubySize = src.rubySize;

		_rubySize = src._rubySize;

		defaultRubyOffset = src.defaultRubyOffset;

		rubyOffset = src.rubyOffset;

		_rubyOffset = src._rubyOffset;

		defaultLineSpacing = src.defaultLineSpacing;

		lineSpacing = src.lineSpacing;

		defaultPitch = src.defaultPitch;

		pitch = src.pitch;

		defaultShadow = src.defaultShadow;

		shadow = src.shadow;

		defaultEdge = src.defaultEdge;

		edge = src.edge;

		defaultShadowColor = src.defaultShadowColor;

		shadowColor = src.shadowColor;

		defaultEdgeColor = src.defaultEdgeColor;

		edgeColor = src.edgeColor;

		defaultBold = src.defaultBold;

		bold = src.bold;

		defaultFace = src.defaultFace;

		userFace = src.userFace;

		fontFace = src.fontFace;

		defaultChColor = src.defaultChColor;

		chColor = src.chColor;

		defaultAntialiased = src.defaultAntialiased;

		antialiased = src.antialiased;

		vertical = src.vertical;

		currentRuby = src.currentRuby;

		lastDrawnCh = src.lastDrawnCh;

		edgeExtent = src.edgeExtent;

		edgeEmphasis = src.edgeEmphasis;

		shadowOffsetX = src.shadowOffsetX;

		shadowOffsetY = src.shadowOffsetY;

		shadowWidth   = src.shadowWidth;

		sizeChanged = src.sizeChanged;

		nextClearFlag = src.nextClearFlag;

		lineLayerBase = src.lineLayerBase;

		lineLayerPos = src.lineLayerPos;

		lineLayerLength = src.lineLayerLength;

		lineLayerOriginX = src.lineLayerOriginX;

		lineLayerOriginY = src.lineLayerOriginY;

		lineLayerPadding = src.lineLayerPadding;

		align = src.align;

		defaultAutoReturn = src.defaultAutoReturn;

		autoReturn = src.autoReturn;

		lineBreakGlyph = src.lineBreakGlyph;

		lineBreakGlyphKey = src.lineBreakGlyphKey;

		pageBreakGlyph = src.pageBreakGlyph;

		pageBreakGlyphKey = src.pageBreakGlyphKey;

		glyphFixedPosition = src.glyphFixedPosition;

		glyphFixedLeft = src.glyphFixedLeft;

		glyphFixedTop = src.glyphFixedTop;

		draggable = src.draggable;

		selClickLock = src.selClickLock;

		lastMouseX = src.lastMouseX;

		lastMouseY = src.lastMouseY;

		// [end_assign_vars]



        // Name layer

        if (src.nameLayer !== void) {

            initNameLayer();

			with (nameLayer) {

				.assignImages(src.nameLayer, true);

				.align  = src.nameLayer.align;

				.valign = src.nameLayer.valign;

			}

        } else {

            invalidateNameLayer();

        }



        // Expression layer

        if (src.faceLayer !== void) {

            initFaceLayer();

            faceLayer.assignImages(src.faceLayer, true);

        } else {

            invalidateFaceLayer();

        }



		if (subLayers !== void && src.subLayers !== void) {

			for (var i = subLayers.count-1; i >= 0; i--)

				subLayers[i].assign(src.subLayers[i]);

		}



        timeoutTime    = src.timeoutTime;

        timeoutStorage = src.timeoutStorage;

        timeoutTarget  = src.timeoutTarget;

        timeoutExp     = src.timeoutExp;



        clickStorage = src.clickStorage;

        clickTarget  = src.clickTarget;

        clickExp     = src.clickExp;

        

        // System button copy process

		clearSystemButtons();

		// Copy generation info

		buttons_save.assign(src.buttons_save);



		// Dictionary foreach cannot be used because it doesn't maintain addition order

		/*

        foreach(src.buttons, function(name,value,srcbuttons,self) {

            // Clone process

            var b = new SystemButtonLayer(self.window, self);

            b.assign(value);

            self.buttons[name] = b;

        }, this);

		 */



		// Clone process from buttons_save info

		for (var i = 0; i < buttons_save.count; i++) {

			var elm = buttons_save[i];

			var to = new SystemButtonLayer(window, this);

			var name = elm.name != "" ? elm.name : ("sysbutton" + i);

			var from = src.buttons[name];

			if (from !== void) to.assign(from);

			else {

				dm("MessageLayer.internalAssign: SystemButton not found:" + name);

				to.name = name;

				to.visible = false;

			}

			buttons[name] = to;

		}



		// For redrawTextStates

		if (src.redrawTextStates === void) redrawTextStates = void;

		else {

			redrawTextStates = [];

			redrawTextStates.assign(src.redrawTextStates);

		}

    }



	function assign(src)

	{

		internalAssign(src, true);

	}



	function store()

	{

		// Record current state into dictionary array and return it

		// Between [start_store_vars] and [end_store_vars]

		// (omitted)

		var dic = super.store();

		// [start_store_vars]

		dic.frameGraphic = frameGraphic;

		dic.frameKey = frameKey;

        dic.frameAnimCount = frameAnimCount;

        dic.frameAnimTime = frameAnimTime;

        dic.frameColor = frameColor;

		dic.frameOpacity = frameOpacity;

		dic.marginL = marginL;

		dic.marginT = marginT;

		dic.marginR = marginR;

		dic.marginB = marginB;

		dic.marginRCh = marginRCh;

		dic.defaultLinkColor = defaultLinkColor;

		dic.defaultLinkOpacity = defaultLinkOpacity;

		dic.defaultFontSize = defaultFontSize;

		dic.nameLayerFontSize = nameLayerFontSize;

		dic.defaultLineSize = defaultLineSize;

		dic.defaultRubySize = defaultRubySize;

		dic.defaultRubyOffset = defaultRubyOffset;

		dic.defaultLineSpacing = defaultLineSpacing;

		dic.defaultPitch = defaultPitch;

		dic.defaultShadow = defaultShadow;

		dic.defaultEdge = defaultEdge;

		dic.defaultShadowColor = defaultShadowColor;

		dic.defaultEdgeColor = defaultEdgeColor;

		dic.defaultBold = defaultBold;

		dic.defaultFace = defaultFace;

		dic.defaultChColor = defaultChColor;

		dic.vertical = vertical;

		dic.edgeExtent = edgeExtent;

		dic.edgeEmphasis = edgeEmphasis;

		dic.shadowOffsetX = shadowOffsetX;

		dic.shadowOffsetY = shadowOffsetY;

		dic.shadowWidth   = shadowWidth;

		dic.defaultAutoReturn = defaultAutoReturn;

		dic.lineBreakGlyph = lineBreakGlyph;

		dic.lineBreakGlyphKey = lineBreakGlyphKey;

		dic.pageBreakGlyph = pageBreakGlyph;

		dic.pageBreakGlyphKey = pageBreakGlyphKey;

		dic.glyphFixedPosition = glyphFixedPosition;

		dic.glyphFixedLeft = glyphFixedLeft;

		dic.glyphFixedTop = glyphFixedTop;

        dic.draggable = draggable;

        dic.eventTransparent = eventTransparent;

        // [end_store_vars]

        dic.faceLayer = faceLayer.store() if faceLayer !== void;

        dic.nameLayer = nameLayer.store() if nameLayer !== void;

        dic.buttons = [];

        dic.buttons.assign(buttons_save);

        return dic;

	}



	function restore(dic)

	{

		imageModified = true;

		// Read state from dic

		// Between [start_restore_vars] and [end_restore_vars]

		// (omitted)

		// [start_restore_vars]

		frameGraphic = dic.frameGraphic if dic.frameGraphic !== void;

		frameKey = dic.frameKey if dic.frameKey !== void;

        frameAnimCount = dic.frameAnimCount if dic.frameAnimCount !== void;

        frameAnimTime = dic.frameAnimTime if dic.frameAnimTime !== void;

        frameColor = dic.frameColor if dic.frameColor !== void;

		frameOpacity = dic.frameOpacity if dic.frameOpacity !== void;

		marginL = dic.marginL if dic.marginL !== void;

		marginT = dic.marginT if dic.marginT !== void;

		marginR = dic.marginR if dic.marginR !== void;

		marginB = dic.marginB if dic.marginB !== void;

		marginRCh = dic.marginRCh if dic.marginRCh !== void;

		defaultLinkColor = dic.defaultLinkColor if dic.defaultLinkColor !== void;

		defaultLinkOpacity = dic.defaultLinkOpacity if dic.defaultLinkOpacity !== void;

		defaultFontSize = dic.defaultFontSize if dic.defaultFontSize !== void;

		nameLayerFontSize = dic.nameLayerFontSize if dic.nameLayerFontSize !== void;

		defaultLineSize = dic.defaultLineSize if dic.defaultLineSize !== void;

		defaultRubySize = dic.defaultRubySize if dic.defaultRubySize !== void;

		defaultRubyOffset = dic.defaultRubyOffset if dic.defaultRubyOffset !== void;

		defaultLineSpacing = dic.defaultLineSpacing if dic.defaultLineSpacing !== void;

		defaultPitch = dic.defaultPitch if dic.defaultPitch !== void;

		defaultShadow = dic.defaultShadow if dic.defaultShadow !== void;

		defaultEdge = dic.defaultEdge if dic.defaultEdge !== void;

		defaultShadowColor = dic.defaultShadowColor if dic.defaultShadowColor !== void;

		defaultEdgeColor = dic.defaultEdgeColor if dic.defaultEdgeColor !== void;

		defaultBold = dic.defaultBold if dic.defaultBold !== void;

		defaultFace = dic.defaultFace if dic.defaultFace !== void;

		defaultChColor = dic.defaultChColor if dic.defaultChColor !== void;

		vertical = dic.vertical if dic.vertical !== void;

		edgeExtent = dic.edgeExtent if dic.edgeExtent !== void;

		edgeEmphasis = dic.edgeEmphasis if dic.edgeEmphasis !== void;

		shadowOffsetX = dic.shadowOffsetX if dic.shadowOffsetX !== void;

		shadowOffsetY = dic.shadowOffsetY if dic.shadowOffsetY !== void;

		shadowWidth   = dic.shadowWidth   if dic.shadowWidth   !== void;

		defaultAutoReturn = dic.defaultAutoReturn if dic.defaultAutoReturn !== void;

		lineBreakGlyph = dic.lineBreakGlyph if dic.lineBreakGlyph !== void;

		lineBreakGlyphKey = dic.lineBreakGlyphKey if dic.lineBreakGlyphKey !== void;

		pageBreakGlyph = dic.pageBreakGlyph if dic.pageBreakGlyph !== void;

		pageBreakGlyphKey = dic.pageBreakGlyphKey if dic.pageBreakGlyphKey !== void;

		glyphFixedPosition = dic.glyphFixedPosition if dic.glyphFixedPosition !== void;

		glyphFixedLeft = dic.glyphFixedLeft if dic.glyphFixedLeft !== void;

		glyphFixedTop = dic.glyphFixedTop if dic.glyphFixedTop !== void;

		draggable = dic.draggable if dic.draggable !== void;

        eventTransparent = dic.eventTransparent if dic.eventTransparent !== void;

        // [end_restore_vars]

		if (!dic.noFaceRestore) {

			if (dic.faceLayer !== void) {

				initFaceLayer();

				faceLayer.restore(dic.faceLayer);

			} else {

				invalidateFaceLayer();

			}

		}

        if (dic.nameLayer !== void) {

            initNameLayer();

            nameLayer.restore(dic.nameLayer);

        } else {

            invalidateNameLayer();

        }

        // System button recovery process

        clearSystemButtons();

        var bt = dic.buttons;

        if (bt !== void) {

            for (var i=0;i<bt.count;i++) {

                addSystemButton(bt[i]);

            }

        }

        super.restore(dic);

	}



	function atEndOfTransition(src, withchildren, exchange)

	{

		// Override atEndOfTransition

		super.atEndOfTransition(...);

		if(src == null)

		{

			//- Transition of message/foreground layers without src (children=true)

			// Nothing needs to be done, but child layers automatically hide after end.

		}

		else

		{

			//- Transition of message/foreground layers with src (children=true)

			// Swap important info with transition source. If exchange=false, further copy 

			// transition source's info to transition destination. However, do not copy 

			// window visibility information during this copy.

			assign(src, false);

			exchangeInfo();

			window.swapMessageLayer(id);

		}

	}



	function assignTransSrc()

	{

		// Copy transition source

		assign(comp, true);

	}



	function exchangeInfo()

	{

		// Exchange information with comp.

		// Since images and tree structure have already been swapped, swap names etc.

		// Also update window management information.

		var src = comp;

		var tmp = src.name;

		src.name = name;

		name = tmp;



        if (src.nameLayer !== void) {

            initNameLayer();

            tmp = src.nameLayer.name;

            src.nameLayer.name = nameLayer.name;

            nameLayer.name = tmp;

        }



        if (src.faceLayer !== void) {

            initFaceLayer();

            tmp = src.faceLayer.name;

            src.faceLayer.name = faceLayer.name;

            faceLayer.name = tmp;

        }

    }



	function setHiddenStateByUser(b)

	{

		// Called when user temporarily hides message layer (e.g. by right clicking).

		if(b)

		{

			visibleBeforeUserInvisible = visible;

			invisibleByUser = true; // Temporarily invisible by user

			visible = false;

		}

		else

		{

			invisibleByUser = false; // Visible

			visible = visibleBeforeUserInvisible;

		}

	}

}





// TJS Script ends here

"

END_OF_TJS_SCRIPT

# "; /*



# Perl script to regenerate variables to be copied in assign/store/restore



open FH, "MessageLayer.tjs" or die;

undef($/);

$content = <FH>;



$list_assign = '';

$list_store = '';

$list_restore = '';

while($content =~ /\/\*(\w+)\*\/var\s+(\w+)/gs)

{

	$a = $1;

	$v = $2;

	if($a =~ /C/)

	{ $list_assign .= "\t\t$v = src.$v;\n"; }

	if($a =~ /S/)

	{

		$list_store .= "\t\tdic.$v = $v;\n";

		$list_restore .= "\t\t$v = dic.$v if dic.$v !== void;\n";

	}

}



$content =~

s/\t\t\/\/ \[start_assign_vars\]\n.*?\t\t\/\/ \[end_assign_vars\]/\t\t\/\/ \[start_assign_vars\]\n$list_assign\t\t\/\/ \[end_assign_vars\]/s;

$content =~

s/\t\t\/\/ \[start_store_vars\]\n.*?\t\t\/\/ \[end_store_vars\]/\t\t\/\/ \[start_store_vars\]\n$list_store\t\t\/\/ \[end_store_vars\]/s;

$content =~

s/\t\t\/\/ \[start_restore_vars\]\n.*?\t\t\/\/ \[end_restore_vars\]/\t\t\/\/ \[start_restore_vars\]\n$list_restore\t\t\/\/ \[end_restore_vars\]/s;



open FH, ">MessageLayer.tjs" or die;

print FH $content;





# */