{
	var throw_system_not_found =
		function
		{
			throw new Exception(
				"System not found\n"
				"This introductory script will not function properly unless the\n"
				"folder/file configuration is the same as when KAG is distributed.");
		};

	if(Storages.isExistentStorage("../template/system/Initialize.tjs"))	{
		Storages.addAutoPath("../template/system/");
		Scripts.execStorage("../template/system/Initialize.tjs");
	} else {
		throw_system_not_found();
	}
}